/*
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IfictiondslStandaloneSetup extends IfictiondslStandaloneSetupGenerated {

	def static void doSetup() {
		new IfictiondslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
