/**
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IfictiondslUiModule extends AbstractIfictiondslUiModule {
  public IfictiondslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
