/*
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IfictiondslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("net/mudcrab/coursework/mbsd/parser/antlr/internal/InternalIfictiondsl.tokens");
	}
}
