/*
 * generated by Xtext 2.42.0
 */
package net.mudcrab.coursework.mbsd.validation

import java.util.HashMap
import java.util.HashSet
import java.util.List
import net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption
import net.mudcrab.coursework.mbsd.ifictiondsl.Comparison
import net.mudcrab.coursework.mbsd.ifictiondsl.Condition
import net.mudcrab.coursework.mbsd.ifictiondsl.Node
import net.mudcrab.coursework.mbsd.ifictiondsl.Story
import net.mudcrab.coursework.mbsd.ifictiondsl.SystemStateChangeNode
import net.mudcrab.coursework.mbsd.ifictiondsl.Transition
import org.eclipse.xtext.EcoreUtil2
import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.validation.CheckType
import net.mudcrab.coursework.mbsd.ifictiondsl.Parentheses

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class IfictiondslValidator extends AbstractIfictiondslValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					IfictiondslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check(CheckType.FAST)
	def checkNotRefferencedByAnyTransitions(Story story) {
		System.out.println("checkNotRefferencedByAnyTransitions called")
		val allTransitions = EcoreUtil2.getAllContentsOfType(story, Transition)
		for (node : getNodesNotRefferencedByAnyTransitions(story, allTransitions)) {
			warning("Node with name '" + node.name + "' is not referenced by any transitions!",
				node,
				null,
				"Node-is-Dead"
			)
		}
	}

	@Check(CheckType.NORMAL) 
	def checkDetectDeadLeaves(Story story) {
		System.out.println("checkDetectDeadLeaves called")
		
		val traverser = new ASTTraverser()
		traverser.traverseStory(story)
		val allTransitions = EcoreUtil2.getAllContentsOfType(story, Transition)
		
		// check if any nodes have not been visited -> dead node candidates
		var HashSet<Node> deadNodeCandidates = new HashSet<Node>()
		for (node : story.nodes) {
			if (!traverser.visitedNodes.containsKey(node)) {
				deadNodeCandidates.add(node)
			}
		}
		
		// filter out not referenced by transitions they are covered by other @Check
		for (notRefedNode : getNodesNotRefferencedByAnyTransitions(story, allTransitions)) {
			deadNodeCandidates.remove(notRefedNode)
		}
		
		// Find transition candidates that can get to the dead node candidate
			// For each transition check if the corresponding node has been visited - if not skip
			// If no transition exists that corresponds to a visited node, then the node must be further down the dead branch and node should be skipped i.e. removed 
		var HashSet<Transition> transitionCandidates = new HashSet<Transition>()
		
		for(deadNodeCand : deadNodeCandidates.toArray) {		
			var boolean keep = false
			for (transition : allTransitions) {
				if (transition.destination === deadNodeCand) {
					var container = transition.eContainer
					if (container instanceof ChoiceOption) {
						container = container.eContainer
					}
					if (traverser.visitedNodes.containsKey(container)) {
						transitionCandidates.add(transition)
						keep = true
					}
				}
			}
			if(!keep) {
				keep = false				
				deadNodeCandidates.remove(deadNodeCand)
			}
		}
		
		// Maybe there exists a state in the collection of visited notes that satisfies any of the transition conditions of the dead node candidates
		// if so, try to get to dead node from nodes that hold an acceptable state
		// if node is reached now. remove from list
		var int deadNodeCandidateCount 
		do {	
			deadNodeCandidateCount = deadNodeCandidates.length		
			for (transCand : transitionCandidates) {
				val travNodesWithRightState = new HashMap<Node,TraversalNode>(traverser.visitedNodes).values.filter[
					ASTTraverser.checkCondition(transCand.condition, it.stateSnapshot)
				]
				for (travNode : travNodesWithRightState) {					
					if (travNode !== null &&
						traverser.findNodeFrom(travNode.node, transCand.destination)
					) {
						System.out.println("Found at least one new node")
					}
				}
			}
			for (deadNodeCand : deadNodeCandidates.toArray) {
				if (traverser.visitedNodes.containsKey(deadNodeCand)) {
					System.out.println("Removed a node from candidates: " + (deadNodeCand as Node).name)
					deadNodeCandidates.remove(deadNodeCand)
					transitionCandidates.remove(
						transitionCandidates.findFirst[
							it.destination.equals(deadNodeCand)
						]
					)
				}
			}
		} while (deadNodeCandidateCount > deadNodeCandidates.length)
		
		System.out.println("Got here 1")
		
		// Analyse what condition needs to be met by system state from state fetched by the TraversalNode 
		// containing node with transition to dead node candidate
		for (transCand : transitionCandidates) {
			analyseConditionAndTryToFulfillIt(transCand.condition, traverser)
		}
		
	
		System.out.println("Got here final")
	}
	
	private def boolean analyseConditionAndTryToFulfillIt(Condition condition, ASTTraverser traverser) {
		val TraversalCondition travCond = new TraversalCondition(condition)
		var boolean isConditionFulfillable = false
		while(!isConditionFulfillable && travCond.buildNextComparisonChain()) {
			// now the first Comparison of the first top level And Condition is isolated
			val firstFailedComparison = travCond.comparisonChain.findFirst[ comp | // find the first that fails -> returns true
				switch(comp) {
					Comparison: {
						// First check if comparison is already achieved
						while(!checkIfComparisonIsAlreadyAchieved(comp, traverser)) {				
							// Now check if any known state change node can move us in the right direction
							val scnode = getFirstVisitedStateChangeNodeThatCanHelpAchieveComparison(comp, traverser)	
							if(scnode !== null) {
								// Find node with state that can get us to the state change node and try to go there
								val nodeWithRightStateToGetToScnode = traverser.visitedNodes.values.findFirst[
									ASTTraverser.checkCondition(
										traverser.visitedTransitions.findFirst[
											it.destination === scnode	
										].condition, 
										it.stateSnapshot
									)
								].node
								if (!traverser.findNodeFrom(
									nodeWithRightStateToGetToScnode, // traverser.visitedNodes.get(scnode).prevNode.node,
									scnode
									)) {
									return true
								}
							}							
						}
					}
					Parentheses: {
						if (!analyseConditionAndTryToFulfillIt(comp.inner, traverser)) {
							return true
						}
					}
				}
			]
			isConditionFulfillable = firstFailedComparison === null
		}
		return isConditionFulfillable
	}
	
	private def boolean checkIfComparisonIsAlreadyAchieved(Comparison comp, ASTTraverser traverser) {
		// First check all visited nodes to see if comparison is already achieved somewhere
		for (travNode : traverser.visitedNodes.values) {
			if (travNode.stateSnapshot.containsKey(comp.variable) ) {
				if (travNode.stateSnapshot.get(comp.variable) === comp.value) {
					return true
				}
			}
		}
	}
		
	private def SystemStateChangeNode getFirstVisitedStateChangeNodeThatCanHelpAchieveComparison(Comparison comp, ASTTraverser traverser) {
		for (scnode : traverser.visitedStateChangeNodes) {
			for (stateUpdate : scnode.stateUpdates) {
				if (stateUpdate.variable.equals(comp.variable)) {
					if ("=".equals(stateUpdate.operator)) {
						if ("<= >= ==".contains(comp.operator)) {
							return stateUpdate.value === comp.value ? scnode : null
						} else {
							return null
						}
					} else {
						// system state does not satisfy cond 
						if ("< <=".contains(comp.operator)) {
							// - so state is higher than target - in case of "+=": direction to target is different than direction of state change
							return "-=".equals(stateUpdate.operator) ? scnode : null
						}
						if ("> >=".contains(comp.operator)) {
							// - so state is lower than target - in case of "+=": direction to target is the same as direction of state change
							return "+=".equals(stateUpdate.operator) ? scnode : null
						}
						if ("==".equals(comp.operator)) {
							if (stateUpdate.value < comp.value ) {
								// state is higher than target - direction to target is different than direction of state change
								return null
							} else { // state is lower than target
								// need to be able to hit target exactly - depends on system state
								for (travNode : traverser.visitedNodes.values) {
									if (travNode.stateSnapshot.get(comp.variable) + comp.value % stateUpdate.value == 0) {
										return scnode
									}
								}	
								return null
							}
						}
					}
				}
			}
		}
	}
	
	private def HashSet<Node> getNodesNotRefferencedByAnyTransitions(Story story, List<Transition> allTransitions) {
		var HashSet<Node> notRefferencedByTransitions = new HashSet<Node>(story.nodes)
		for (t : allTransitions) {
			if (notRefferencedByTransitions.contains(t.destination)) {
				notRefferencedByTransitions.remove(t.destination)
			}
		}
		return notRefferencedByTransitions
	}
	
}
