/*
 * generated by Xtext 2.42.0
 */
package net.mudcrab.coursework.mbsd.validation

import java.util.HashMap
import java.util.HashSet
import java.util.List
import net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption
import net.mudcrab.coursework.mbsd.ifictiondsl.Comparison
import net.mudcrab.coursework.mbsd.ifictiondsl.Condition
import net.mudcrab.coursework.mbsd.ifictiondsl.Node
import net.mudcrab.coursework.mbsd.ifictiondsl.Parentheses
import net.mudcrab.coursework.mbsd.ifictiondsl.Story
import net.mudcrab.coursework.mbsd.ifictiondsl.SystemStateChangeNode
import net.mudcrab.coursework.mbsd.ifictiondsl.Transition
import org.eclipse.emf.ecore.util.EcoreUtil
import org.eclipse.xtext.EcoreUtil2
import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.validation.CheckType
import net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class IfictiondslValidator extends AbstractIfictiondslValidator {
	
	public static val NOT_REFERENCED_BY_TRANSITION = 'notReferencedByTransition'

//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					IfictiondslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

//	@Check(CheckType.FAST)
//	def checkNotRefferencedByAnyTransitions(Node node) {
//		System.out.println("checkNotRefferencedByAnyTransitions called")
//		val allTransitions = EcoreUtil2.getAllContentsOfType(node.eContainer, Transition)
//		if(allTransitions.findFirst[it.destination === node] === null) {
//			warning("Node with name '" + node.name + "' is not referenced by any transitions!",
//				node,
//				null,
//				NOT_REFERENCED_BY_TRANSITION
//			)
//		}
//	}

	@Check(CheckType.FAST)
	def checkNotRefferencedByAnyTransitions(Node node) {
		System.out.println("checkNotRefferencedByAnyTransitions called")
		if(EcoreUtil.UsageCrossReferencer.find(node, node.eContainer).size === 0) {
			warning('''Node with name '«node.name»' is not referenced by any transitions!''',
				IfictiondslPackage.Literals.NODE__NAME,
				NOT_REFERENCED_BY_TRANSITION
			)
		}
	}

	@Check(CheckType.NORMAL) 
	def checkDetectDeadLeaves(Story story) {
		System.out.println("checkDetectDeadLeaves called")
		
		val traverser = new ASTTraverser()
		traverser.traverseStory(story)
		val allTransitions = EcoreUtil2.getAllContentsOfType(story, Transition)
		
		// check if any nodes have not been visited -> dead node candidates
		var HashSet<Node> deadNodeCandidates = new HashSet<Node>()
		for (node : story.nodes) {
			if (!traverser.visitedNodes.containsKey(node)) {
				deadNodeCandidates.add(node)
			}
		}
		
		// filter out not referenced by transitions they are covered by other @Check
		for (notRefedNode : getNodesNotRefferencedByAnyTransitions(story, allTransitions)) {
			deadNodeCandidates.remove(notRefedNode)
		}
		
		// Find transition candidates that can get to the dead node candidate
			// For each transition check if the corresponding node has been visited - if not skip
			// If no transition exists that corresponds to a visited node, then the node must be further down the dead branch and node should be skipped i.e. removed 
		var HashSet<Transition> transitionCandidates = new HashSet<Transition>()
		
		for(deadNodeCand : deadNodeCandidates.toArray) {		
			var boolean keep = false
			for (transition : allTransitions) {
				if (transition.destination === deadNodeCand) {
					var container = transition.eContainer
					if (container instanceof ChoiceOption) {
						container = container.eContainer
					}
					if (traverser.visitedNodes.containsKey(container)) {
						transitionCandidates.add(transition)
						keep = true
					}
				}
			}
			if(!keep) {
				keep = false				
				deadNodeCandidates.remove(deadNodeCand)
			}
		}
		
		// Maybe there exists a state in the collection of visited notes that satisfies any of the transition conditions of the dead node candidates
		// if so, try to get to dead node from nodes that hold an acceptable state
		// if node is reached now. remove from list
		var int deadNodeCandidateCount 
		do {	
			deadNodeCandidateCount = deadNodeCandidates.length		
			for (transCand : transitionCandidates) {
				val travNodesWithRightState = new HashMap<Node,TraversalNode>(traverser.visitedNodes).values.filter[
					ASTTraverser.checkCondition(transCand.condition, it.stateSnapshot)
				]
				for (travNode : travNodesWithRightState) {					
					if (travNode !== null &&
						traverser.findNodeFrom(travNode.node, transCand.destination)
					) {
						System.out.println("Found at least one new node")
					}
				}
			}
			for (deadNodeCand : deadNodeCandidates.toArray) {
				if (traverser.visitedNodes.containsKey(deadNodeCand)) {
					System.out.println("Removed a node from candidates: " + (deadNodeCand as Node).name)
					deadNodeCandidates.remove(deadNodeCand)
					transitionCandidates.remove(
						transitionCandidates.findFirst[
							it.destination.equals(deadNodeCand)
						]
					)
				}
			}
		} while (deadNodeCandidateCount > deadNodeCandidates.length)
		
		System.out.println("Got here 1")
		
		// Analyse what condition needs to be met by system state from state fetched by the TraversalNode 
		// containing node with transition to dead node candidate
		// start out by sorting by priority! some transitions might be shadowed by others by priority
		val transCandidatedsSortedByPriority = transitionCandidates.sortBy[ -it.priority ] // '-' because decending order
		for (transCand : transCandidatedsSortedByPriority) {
			if (analyseConditionAndTryToFulfillItByTraversingAST(transCand.condition, traverser)) {
				System.out.println("Condition was fulfilled")
			}
		}
		
	
		System.out.println("Got here final")
	}
	
	private def boolean analyseConditionAndTryToFulfillItByTraversingAST(Condition condition, ASTTraverser traverser) {
		// First of all. is root condition already met?
		if (!(condition.eContainer instanceof Condition)) {			
			val travNodesWithRightState = traverser.visitedNodes.values.filter[
				ASTTraverser.checkCondition(condition, it.stateSnapshot)
			]
			if (travNodesWithRightState.size > 0) {
				System.out.println("Got here inside")
				for (travNode : travNodesWithRightState) {
					System.out.println(travNode + ", " + condition)
				}
			}
		}
		val TraversalCondition travCond = new TraversalCondition(condition)
		var boolean isConditionFulfillable = true
		while(isConditionFulfillable && travCond.buildNextComparisonChain()) {
			// now the first Comparison of the first top level And Condition is isolated
			val firstFailedComparison = travCond.comparisonChain.findFirst[ comp | // find the first that fails i.e. reason for And-chain fail -> returns true
				switch(comp) {
					Comparison: {
						// First check if comparison is already achieved
						if(!checkIfComparisonIsAlreadyAchieved(comp, traverser)) {				
							// Now check if any known state change node can move us in the right direction
							val scnodes = getVisitedStateChangeNodesThatCanHelpAchieveComparison(comp, traverser)
							if (scnodes.size === 0) 
								return false
							for (scnode :  scnodes) {
								// Find node with state that can get us to the state change node and try to go there
								var nodeWithRightStateToGetToScnode = traverser.visitedNodes.values.findFirst[
									ASTTraverser.checkCondition(
										traverser.visitedTransitions.findFirst[
											it.destination === scnode	
										].condition, 
										it.stateSnapshot 
									) && it !== scnode
								].node
								var boolean keepSearching = true
								while(keepSearching && traverser.findNodeFrom(
														 nodeWithRightStateToGetToScnode, // traverser.visitedNodes.get(scnode).prevNode.node,
														 scnode,
														 true 
													   ) 
								){
									keepSearching = !checkIfComparisonIsAlreadyAchieved(comp, traverser)
									nodeWithRightStateToGetToScnode = scnode // the only node with right state now is the scnode
								}
								return !checkIfComparisonIsAlreadyAchieved(comp, traverser)
							}							
						}
					}
					Parentheses: {
						return analyseConditionAndTryToFulfillItByTraversingAST(comp.inner, traverser)
					}
				}
				return false
			]
			isConditionFulfillable = firstFailedComparison !== null
		}
		return isConditionFulfillable
	}
	
	private def boolean checkIfComparisonIsAlreadyAchieved(Comparison comp, ASTTraverser traverser) {
		// First check all visited nodes to see if comparison is already achieved somewhere
		for (travNode : traverser.visitedNodes.values) {
			if (travNode.stateSnapshot.containsKey(comp.variable) ) {
				switch (comp.operator) {
					case "==": { return travNode.stateSnapshot.getOrDefault(comp.variable, 0) == comp.value }
					case "!=": { return travNode.stateSnapshot.getOrDefault(comp.variable, 0) != comp.value }
					case ">": { return travNode.stateSnapshot.getOrDefault(comp.variable, 0) > comp.value }
					case "<": { return travNode.stateSnapshot.getOrDefault(comp.variable, 0) < comp.value }
					case ">=": { return travNode.stateSnapshot.getOrDefault(comp.variable, 0) >= comp.value }
					case "<=": { return travNode.stateSnapshot.getOrDefault(comp.variable, 0) <= comp.value }
				}
			}
		}
	}
	
	// This method is called after checkIfComparisonIsAlreadyAchieved() - prerequisite is that condition is not fulfilled
	private def Iterable<SystemStateChangeNode> getVisitedStateChangeNodesThatCanHelpAchieveComparison(Comparison comp, ASTTraverser traverser) {
		return traverser.visitedStateChangeNodes.filter[ scnode |  
			for (stateUpdate : scnode.stateUpdates) {
				if (stateUpdate.variable.equals(comp.variable)) {
					if ("=".equals(stateUpdate.operator)) {
						// if state update sets the variable to a constant we can only use it if we can match
						if ("<= >= ==".contains(comp.operator)) {
							return stateUpdate.value === comp.value
						} else {
							return false
						}
					} else {
						// system state does not satisfy cond 
						if ("< <=".contains(comp.operator)) {
							// - so state is higher than target - in case of "+=": direction to target is different than direction of state change
							return "-=".equals(stateUpdate.operator)
						}
						if ("> >=".contains(comp.operator)) {
							// - so state is lower than target - in case of "+=": direction to target is the same as direction of state change
							return "+=".equals(stateUpdate.operator)
						}
						if ("==".equals(comp.operator)) {
							// State update does not set a contant but we need to hit a contant
							// need to be able to hit target exactly - depends on system state
							for (travNode : traverser.visitedNodes.values) {
								val current = travNode.stateSnapshot.getOrDefault(comp.variable, 0)
								if ((current - comp.value) % stateUpdate.value == 0) {
								    if (stateUpdate.operator == "-=" && current - stateUpdate.value >= comp.value) 
								    	return true
								    if (stateUpdate.operator == "+=" && current + stateUpdate.value <= comp.value) 
								    	return true
								}
							}	
							return false
						}
					}
				}
			}
			return false
		]
	}
	
	private def HashSet<Node> getNodesNotRefferencedByAnyTransitions(Story story, List<Transition> allTransitions) {
		var HashSet<Node> notRefferencedByTransitions = new HashSet<Node>(story.nodes)
		for (t : allTransitions) {
			if (notRefferencedByTransitions.contains(t.destination)) {
				notRefferencedByTransitions.remove(t.destination)
			}
		}
		return notRefferencedByTransitions
	}
	
}
