/*
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class IfictiondslUiModule extends AbstractIfictiondslUiModule {
}
