/*
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.ui;

import com.google.inject.Injector;
import net.mudcrab.coursework.mbsd.ui.internal.MbsdActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IfictiondslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MbsdActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MbsdActivator activator = MbsdActivator.getInstance();
		return activator != null ? activator.getInjector(MbsdActivator.NET_MUDCRAB_COURSEWORK_MBSD_IFICTIONDSL) : null;
	}

}
