/**
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.ifictiondsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choice Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceNode#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getChoiceNode()
 * @model
 * @generated
 */
public interface ChoiceNode extends Node
{
  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference list.
   * The list contents are of type {@link net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference list.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getChoiceNode_Options()
   * @model containment="true"
   * @generated
   */
  EList<ChoiceOption> getOptions();

} // ChoiceNode
