/**
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.ifictiondsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choice Option</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption#getText <em>Text</em>}</li>
 *   <li>{@link net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption#getTransitions <em>Transitions</em>}</li>
 * </ul>
 *
 * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getChoiceOption()
 * @model
 * @generated
 */
public interface ChoiceOption extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getChoiceOption_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link net.mudcrab.coursework.mbsd.ifictiondsl.Transition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getChoiceOption_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransitions();

} // ChoiceOption
