/**
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.ifictiondsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
} // Condition
