/**
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.ifictiondsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dialogue Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.mudcrab.coursework.mbsd.ifictiondsl.DialogueNode#getText <em>Text</em>}</li>
 *   <li>{@link net.mudcrab.coursework.mbsd.ifictiondsl.DialogueNode#getTransition <em>Transition</em>}</li>
 * </ul>
 *
 * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getDialogueNode()
 * @model
 * @generated
 */
public interface DialogueNode extends Node
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getDialogueNode_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link net.mudcrab.coursework.mbsd.ifictiondsl.DialogueNode#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transition</em>' containment reference.
   * @see #setTransition(Transition)
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getDialogueNode_Transition()
   * @model containment="true"
   * @generated
   */
  Transition getTransition();

  /**
   * Sets the value of the '{@link net.mudcrab.coursework.mbsd.ifictiondsl.DialogueNode#getTransition <em>Transition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transition</em>' containment reference.
   * @see #getTransition()
   * @generated
   */
  void setTransition(Transition value);

} // DialogueNode
