/**
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.ifictiondsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>End Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.mudcrab.coursework.mbsd.ifictiondsl.EndNode#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getEndNode()
 * @model
 * @generated
 */
public interface EndNode extends Node
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getEndNode_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link net.mudcrab.coursework.mbsd.ifictiondsl.EndNode#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

} // EndNode
