/**
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.ifictiondsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parentheses</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.mudcrab.coursework.mbsd.ifictiondsl.Parentheses#getInner <em>Inner</em>}</li>
 * </ul>
 *
 * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getParentheses()
 * @model
 * @generated
 */
public interface Parentheses extends Condition
{
  /**
   * Returns the value of the '<em><b>Inner</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inner</em>' containment reference.
   * @see #setInner(Condition)
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage#getParentheses_Inner()
   * @model containment="true"
   * @generated
   */
  Condition getInner();

  /**
   * Sets the value of the '{@link net.mudcrab.coursework.mbsd.ifictiondsl.Parentheses#getInner <em>Inner</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inner</em>' containment reference.
   * @see #getInner()
   * @generated
   */
  void setInner(Condition value);

} // Parentheses
