/**
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IfictiondslIdeModule extends AbstractIfictiondslIdeModule {
}
