/*
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class IfictiondslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class StoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.Story");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStoryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNodesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNodesNodeParserRuleCall_2_0 = (RuleCall)cNodesAssignment_2.eContents().get(0);
		
		///*Model:
		//    greetings+=Greeting*;
		//Greeting:
		//    'Hello' name=ID '!';
		// */
		//Story:
		//    'Story' name=ID
		//    (nodes+=Node)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'Story' name=ID
		//(nodes+=Node)*
		public Group getGroup() { return cGroup; }
		
		//'Story'
		public Keyword getStoryKeyword_0() { return cStoryKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//(nodes+=Node)*
		public Assignment getNodesAssignment_2() { return cNodesAssignment_2; }
		
		//Node
		public RuleCall getNodesNodeParserRuleCall_2_0() { return cNodesNodeParserRuleCall_2_0; }
	}
	public class NodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.Node");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStartNodeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cChoiceNodeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDialogueNodeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSystemStateChangeNodeParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cEndNodeParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Node:
		//    StartNode | ChoiceNode | DialogueNode | SystemStateChangeNode | EndNode;
		@Override public ParserRule getRule() { return rule; }
		
		//StartNode | ChoiceNode | DialogueNode | SystemStateChangeNode | EndNode
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StartNode
		public RuleCall getStartNodeParserRuleCall_0() { return cStartNodeParserRuleCall_0; }
		
		//ChoiceNode
		public RuleCall getChoiceNodeParserRuleCall_1() { return cChoiceNodeParserRuleCall_1; }
		
		//DialogueNode
		public RuleCall getDialogueNodeParserRuleCall_2() { return cDialogueNodeParserRuleCall_2; }
		
		//SystemStateChangeNode
		public RuleCall getSystemStateChangeNodeParserRuleCall_3() { return cSystemStateChangeNodeParserRuleCall_3; }
		
		//EndNode
		public RuleCall getEndNodeParserRuleCall_4() { return cEndNodeParserRuleCall_4; }
	}
	public class ChoiceNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.ChoiceNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChoiceNodeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cChoicesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cOptionsAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cOptionsChoiceOptionParserRuleCall_6_0_0 = (RuleCall)cOptionsAssignment_6_0.eContents().get(0);
		private final Group cGroup_6_1 = (Group)cGroup_6.eContents().get(1);
		private final Keyword cCommaKeyword_6_1_0 = (Keyword)cGroup_6_1.eContents().get(0);
		private final Assignment cOptionsAssignment_6_1_1 = (Assignment)cGroup_6_1.eContents().get(1);
		private final RuleCall cOptionsChoiceOptionParserRuleCall_6_1_1_0 = (RuleCall)cOptionsAssignment_6_1_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//ChoiceNode:
		//    'ChoiceNode' name=ID '{'
		//        'choices' ':' '['
		//            (options+=ChoiceOption (',' options+=ChoiceOption)*)?
		//            ']'
		//        '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ChoiceNode' name=ID '{'
		//    'choices' ':' '['
		//        (options+=ChoiceOption (',' options+=ChoiceOption)*)?
		//        ']'
		//    '}'
		public Group getGroup() { return cGroup; }
		
		//'ChoiceNode'
		public Keyword getChoiceNodeKeyword_0() { return cChoiceNodeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'choices'
		public Keyword getChoicesKeyword_3() { return cChoicesKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5() { return cLeftSquareBracketKeyword_5; }
		
		//(options+=ChoiceOption (',' options+=ChoiceOption)*)?
		public Group getGroup_6() { return cGroup_6; }
		
		//options+=ChoiceOption
		public Assignment getOptionsAssignment_6_0() { return cOptionsAssignment_6_0; }
		
		//ChoiceOption
		public RuleCall getOptionsChoiceOptionParserRuleCall_6_0_0() { return cOptionsChoiceOptionParserRuleCall_6_0_0; }
		
		//(',' options+=ChoiceOption)*
		public Group getGroup_6_1() { return cGroup_6_1; }
		
		//','
		public Keyword getCommaKeyword_6_1_0() { return cCommaKeyword_6_1_0; }
		
		//options+=ChoiceOption
		public Assignment getOptionsAssignment_6_1_1() { return cOptionsAssignment_6_1_1; }
		
		//ChoiceOption
		public RuleCall getOptionsChoiceOptionParserRuleCall_6_1_1_0() { return cOptionsChoiceOptionParserRuleCall_6_1_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_7() { return cRightSquareBracketKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ChoiceOptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.ChoiceOption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChoiceOptionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cDisplayTextKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTextAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTextSTRINGTerminalRuleCall_4_0 = (RuleCall)cTextAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cTransitionsAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cTransitionsTransitionParserRuleCall_6_0_0 = (RuleCall)cTransitionsAssignment_6_0.eContents().get(0);
		private final Group cGroup_6_1 = (Group)cGroup_6.eContents().get(1);
		private final Keyword cCommaKeyword_6_1_0 = (Keyword)cGroup_6_1.eContents().get(0);
		private final Assignment cTransitionsAssignment_6_1_1 = (Assignment)cGroup_6_1.eContents().get(1);
		private final RuleCall cTransitionsTransitionParserRuleCall_6_1_1_0 = (RuleCall)cTransitionsAssignment_6_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//ChoiceOption:
		//    'ChoiceOption' '{'
		//        'displayText' ':' text=STRING ','
		//        (transitions+=Transition (',' transitions+=Transition)*)
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ChoiceOption' '{'
		//    'displayText' ':' text=STRING ','
		//    (transitions+=Transition (',' transitions+=Transition)*)
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ChoiceOption'
		public Keyword getChoiceOptionKeyword_0() { return cChoiceOptionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'displayText'
		public Keyword getDisplayTextKeyword_2() { return cDisplayTextKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//text=STRING
		public Assignment getTextAssignment_4() { return cTextAssignment_4; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_4_0() { return cTextSTRINGTerminalRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//(transitions+=Transition (',' transitions+=Transition)*)
		public Group getGroup_6() { return cGroup_6; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_6_0() { return cTransitionsAssignment_6_0; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_6_0_0() { return cTransitionsTransitionParserRuleCall_6_0_0; }
		
		//(',' transitions+=Transition)*
		public Group getGroup_6_1() { return cGroup_6_1; }
		
		//','
		public Keyword getCommaKeyword_6_1_0() { return cCommaKeyword_6_1_0; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_6_1_1() { return cTransitionsAssignment_6_1_1; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_6_1_1_0() { return cTransitionsTransitionParserRuleCall_6_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDestinationAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cDestinationNodeCrossReference_1_0 = (CrossReference)cDestinationAssignment_1.eContents().get(0);
		private final RuleCall cDestinationNodeIDTerminalRuleCall_1_0_1 = (RuleCall)cDestinationNodeCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cWithKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cPriorityKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cPriorityAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cPriorityINTTerminalRuleCall_2_2_0 = (RuleCall)cPriorityAssignment_2_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cWithKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cConditionKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Keyword cColonKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Assignment cConditionAssignment_3_3 = (Assignment)cGroup_3.eContents().get(3);
		private final RuleCall cConditionConditionParserRuleCall_3_3_0 = (RuleCall)cConditionAssignment_3_3.eContents().get(0);
		
		//Transition:
		//    '->' destination=[Node]
		//    ('with' 'priority' priority=INT)?
		//    ('with' 'condition' ':' condition=Condition)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'->' destination=[Node]
		//('with' 'priority' priority=INT)?
		//('with' 'condition' ':' condition=Condition)?
		public Group getGroup() { return cGroup; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_0() { return cHyphenMinusGreaterThanSignKeyword_0; }
		
		//destination=[Node]
		public Assignment getDestinationAssignment_1() { return cDestinationAssignment_1; }
		
		//[Node]
		public CrossReference getDestinationNodeCrossReference_1_0() { return cDestinationNodeCrossReference_1_0; }
		
		//ID
		public RuleCall getDestinationNodeIDTerminalRuleCall_1_0_1() { return cDestinationNodeIDTerminalRuleCall_1_0_1; }
		
		//('with' 'priority' priority=INT)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'with'
		public Keyword getWithKeyword_2_0() { return cWithKeyword_2_0; }
		
		//'priority'
		public Keyword getPriorityKeyword_2_1() { return cPriorityKeyword_2_1; }
		
		//priority=INT
		public Assignment getPriorityAssignment_2_2() { return cPriorityAssignment_2_2; }
		
		//INT
		public RuleCall getPriorityINTTerminalRuleCall_2_2_0() { return cPriorityINTTerminalRuleCall_2_2_0; }
		
		//('with' 'condition' ':' condition=Condition)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'with'
		public Keyword getWithKeyword_3_0() { return cWithKeyword_3_0; }
		
		//'condition'
		public Keyword getConditionKeyword_3_1() { return cConditionKeyword_3_1; }
		
		//':'
		public Keyword getColonKeyword_3_2() { return cColonKeyword_3_2; }
		
		//condition=Condition
		public Assignment getConditionAssignment_3_3() { return cConditionAssignment_3_3; }
		
		//Condition
		public RuleCall getConditionConditionParserRuleCall_3_3_0() { return cConditionConditionParserRuleCall_3_3_0; }
	}
	public class StartNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.StartNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStartNodeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDisplayTextKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTextAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTextSTRINGTerminalRuleCall_5_0 = (RuleCall)cTextAssignment_5.eContents().get(0);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTransitionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTransitionTransitionParserRuleCall_7_0 = (RuleCall)cTransitionAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//StartNode:
		//        'StartNode' name=ID '{'
		//        'displayText' ':' text=STRING ','
		//        transition=Transition
		//        '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'StartNode' name=ID '{'
		//'displayText' ':' text=STRING ','
		//transition=Transition
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'StartNode'
		public Keyword getStartNodeKeyword_0() { return cStartNodeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'displayText'
		public Keyword getDisplayTextKeyword_3() { return cDisplayTextKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//text=STRING
		public Assignment getTextAssignment_5() { return cTextAssignment_5; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_5_0() { return cTextSTRINGTerminalRuleCall_5_0; }
		
		//','
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }
		
		//transition=Transition
		public Assignment getTransitionAssignment_7() { return cTransitionAssignment_7; }
		
		//Transition
		public RuleCall getTransitionTransitionParserRuleCall_7_0() { return cTransitionTransitionParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class DialogueNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.DialogueNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDialogueNodeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDisplayTextKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTextAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTextSTRINGTerminalRuleCall_5_0 = (RuleCall)cTextAssignment_5.eContents().get(0);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTransitionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTransitionTransitionParserRuleCall_7_0 = (RuleCall)cTransitionAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//DialogueNode:
		//        'DialogueNode' name=ID '{'
		//        'displayText' ':' text=STRING ','
		//        transition=Transition
		//        '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'DialogueNode' name=ID '{'
		//'displayText' ':' text=STRING ','
		//transition=Transition
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'DialogueNode'
		public Keyword getDialogueNodeKeyword_0() { return cDialogueNodeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'displayText'
		public Keyword getDisplayTextKeyword_3() { return cDisplayTextKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//text=STRING
		public Assignment getTextAssignment_5() { return cTextAssignment_5; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_5_0() { return cTextSTRINGTerminalRuleCall_5_0; }
		
		//','
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }
		
		//transition=Transition
		public Assignment getTransitionAssignment_7() { return cTransitionAssignment_7; }
		
		//Transition
		public RuleCall getTransitionTransitionParserRuleCall_7_0() { return cTransitionTransitionParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.Condition");
		private final RuleCall cOrConditionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		////===================================================
		//Condition: // entry
		//    OrCondition;
		@Override public ParserRule getRule() { return rule; }
		
		//// entry
		//   OrCondition
		public RuleCall getOrConditionParserRuleCall() { return cOrConditionParserRuleCall; }
	}
	public class OrConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.OrCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndConditionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cOrLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cOrKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAndConditionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//OrCondition returns Condition: // low priority
		//    AndCondition ({Or.left=current} 'or' right=AndCondition)*;
		@Override public ParserRule getRule() { return rule; }
		
		//// low priority
		//   AndCondition ({Or.left=current} 'or' right=AndCondition)*
		public Group getGroup() { return cGroup; }
		
		//// low priority
		//   AndCondition
		public RuleCall getAndConditionParserRuleCall_0() { return cAndConditionParserRuleCall_0; }
		
		//({Or.left=current} 'or' right=AndCondition)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Or.left=current}
		public Action getOrLeftAction_1_0() { return cOrLeftAction_1_0; }
		
		//'or'
		public Keyword getOrKeyword_1_1() { return cOrKeyword_1_1; }
		
		//right=AndCondition
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//AndCondition
		public RuleCall getRightAndConditionParserRuleCall_1_2_0() { return cRightAndConditionParserRuleCall_1_2_0; }
	}
	public class AndConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.AndCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAndLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cAndKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimaryParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//AndCondition returns Condition: // high priority
		//    // Primary ({And.left=current} 'and' right=Primary)*;
		//    Primary ({And.left=current} 'and' right=Primary)*;
		@Override public ParserRule getRule() { return rule; }
		
		//// high priority
		//   // Primary ({And.left=current} 'and' right=Primary)*;
		//   Primary ({And.left=current} 'and' right=Primary)*
		public Group getGroup() { return cGroup; }
		
		//// high priority
		//   // Primary ({And.left=current} 'and' right=Primary)*;
		//   Primary
		public RuleCall getPrimaryParserRuleCall_0() { return cPrimaryParserRuleCall_0; }
		
		//({And.left=current} 'and' right=Primary)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{And.left=current}
		public Action getAndLeftAction_1_0() { return cAndLeftAction_1_0; }
		
		//'and'
		public Keyword getAndKeyword_1_1() { return cAndKeyword_1_1; }
		
		//right=Primary
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Primary
		public RuleCall getRightPrimaryParserRuleCall_1_2_0() { return cRightPrimaryParserRuleCall_1_2_0; }
	}
	public class PrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.Primary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cConditionParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final RuleCall cComparisonParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Primary returns Condition:
		//    '(' Condition ')' | Comparison;
		@Override public ParserRule getRule() { return rule; }
		
		//'(' Condition ')' | Comparison
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'(' Condition ')'
		public Group getGroup_0() { return cGroup_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }
		
		//Condition
		public RuleCall getConditionParserRuleCall_0_1() { return cConditionParserRuleCall_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }
		
		//Comparison
		public RuleCall getComparisonParserRuleCall_1() { return cComparisonParserRuleCall_1; }
	}
	public class ComparisonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.Comparison");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVariableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVariableIDTerminalRuleCall_0_0 = (RuleCall)cVariableAssignment_0.eContents().get(0);
		private final Assignment cOperatorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOperatorOperatorParserRuleCall_1_0 = (RuleCall)cOperatorAssignment_1.eContents().get(0);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueINTTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//Comparison:
		//    (variable=ID operator=Operator value=INT);
		@Override public ParserRule getRule() { return rule; }
		
		//(variable=ID operator=Operator value=INT)
		public Group getGroup() { return cGroup; }
		
		//variable=ID
		public Assignment getVariableAssignment_0() { return cVariableAssignment_0; }
		
		//ID
		public RuleCall getVariableIDTerminalRuleCall_0_0() { return cVariableIDTerminalRuleCall_0_0; }
		
		//operator=Operator
		public Assignment getOperatorAssignment_1() { return cOperatorAssignment_1; }
		
		//Operator
		public RuleCall getOperatorOperatorParserRuleCall_1_0() { return cOperatorOperatorParserRuleCall_1_0; }
		
		//value=INT
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_2_0() { return cValueINTTerminalRuleCall_2_0; }
	}
	public class OperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.Operator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cEqualsSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cExclamationMarkEqualsSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cLessThanSignKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cGreaterThanSignEqualsSignKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cLessThanSignEqualsSignKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//Operator: ('='|'!='|'>'|'<'|'>='|'<=');
		@Override public ParserRule getRule() { return rule; }
		
		//('='|'!='|'>'|'<'|'>='|'<=')
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'='
		public Keyword getEqualsSignKeyword_0() { return cEqualsSignKeyword_0; }
		
		//'!='
		public Keyword getExclamationMarkEqualsSignKeyword_1() { return cExclamationMarkEqualsSignKeyword_1; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_2() { return cGreaterThanSignKeyword_2; }
		
		//'<'
		public Keyword getLessThanSignKeyword_3() { return cLessThanSignKeyword_3; }
		
		//'>='
		public Keyword getGreaterThanSignEqualsSignKeyword_4() { return cGreaterThanSignEqualsSignKeyword_4; }
		
		//'<='
		public Keyword getLessThanSignEqualsSignKeyword_5() { return cLessThanSignEqualsSignKeyword_5; }
	}
	public class SystemStateChangeNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.SystemStateChangeNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSystemStateChangeNodeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDisplayTextKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTextAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTextSTRINGTerminalRuleCall_5_0 = (RuleCall)cTextAssignment_5.eContents().get(0);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cStateUpdatesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cStateUpdatesStateUpdateParserRuleCall_7_0 = (RuleCall)cStateUpdatesAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cStateUpdatesAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cStateUpdatesStateUpdateParserRuleCall_8_1_0 = (RuleCall)cStateUpdatesAssignment_8_1.eContents().get(0);
		private final Assignment cTransitionAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cTransitionTransitionParserRuleCall_9_0 = (RuleCall)cTransitionAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		////===================================================
		////Condition:
		//    //(variable= ID Operator value=INT ('and'|'or' conditions+=Condition)*);
		//SystemStateChangeNode:
		//    'SystemStateChangeNode' name=ID '{'
		//    'displayText' ':' text=STRING ','
		//    stateUpdates+=StateUpdate(',' stateUpdates+=StateUpdate)*
		//    transition=Transition
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'SystemStateChangeNode' name=ID '{'
		//'displayText' ':' text=STRING ','
		//stateUpdates+=StateUpdate(',' stateUpdates+=StateUpdate)*
		//transition=Transition
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'SystemStateChangeNode'
		public Keyword getSystemStateChangeNodeKeyword_0() { return cSystemStateChangeNodeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'displayText'
		public Keyword getDisplayTextKeyword_3() { return cDisplayTextKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//text=STRING
		public Assignment getTextAssignment_5() { return cTextAssignment_5; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_5_0() { return cTextSTRINGTerminalRuleCall_5_0; }
		
		//','
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }
		
		//stateUpdates+=StateUpdate
		public Assignment getStateUpdatesAssignment_7() { return cStateUpdatesAssignment_7; }
		
		//StateUpdate
		public RuleCall getStateUpdatesStateUpdateParserRuleCall_7_0() { return cStateUpdatesStateUpdateParserRuleCall_7_0; }
		
		//(',' stateUpdates+=StateUpdate)*
		public Group getGroup_8() { return cGroup_8; }
		
		//','
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//stateUpdates+=StateUpdate
		public Assignment getStateUpdatesAssignment_8_1() { return cStateUpdatesAssignment_8_1; }
		
		//StateUpdate
		public RuleCall getStateUpdatesStateUpdateParserRuleCall_8_1_0() { return cStateUpdatesStateUpdateParserRuleCall_8_1_0; }
		
		//transition=Transition
		public Assignment getTransitionAssignment_9() { return cTransitionAssignment_9; }
		
		//Transition
		public RuleCall getTransitionTransitionParserRuleCall_9_0() { return cTransitionTransitionParserRuleCall_9_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class StateUpdateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.StateUpdate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVariableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVariableSTRINGTerminalRuleCall_0_0 = (RuleCall)cVariableAssignment_0.eContents().get(0);
		private final Assignment cOperatorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cOperatorAlternatives_1_0 = (Alternatives)cOperatorAssignment_1.eContents().get(0);
		private final Keyword cOperatorPlusSignEqualsSignKeyword_1_0_0 = (Keyword)cOperatorAlternatives_1_0.eContents().get(0);
		private final Keyword cOperatorHyphenMinusEqualsSignKeyword_1_0_1 = (Keyword)cOperatorAlternatives_1_0.eContents().get(1);
		private final Keyword cOperatorEqualsSignKeyword_1_0_2 = (Keyword)cOperatorAlternatives_1_0.eContents().get(2);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueINTTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//StateUpdate:
		//    (variable=STRING operator=('+='|'-='|'=') value=INT);
		@Override public ParserRule getRule() { return rule; }
		
		//(variable=STRING operator=('+='|'-='|'=') value=INT)
		public Group getGroup() { return cGroup; }
		
		//variable=STRING
		public Assignment getVariableAssignment_0() { return cVariableAssignment_0; }
		
		//STRING
		public RuleCall getVariableSTRINGTerminalRuleCall_0_0() { return cVariableSTRINGTerminalRuleCall_0_0; }
		
		//operator=('+='|'-='|'=')
		public Assignment getOperatorAssignment_1() { return cOperatorAssignment_1; }
		
		//('+='|'-='|'=')
		public Alternatives getOperatorAlternatives_1_0() { return cOperatorAlternatives_1_0; }
		
		//'+='
		public Keyword getOperatorPlusSignEqualsSignKeyword_1_0_0() { return cOperatorPlusSignEqualsSignKeyword_1_0_0; }
		
		//'-='
		public Keyword getOperatorHyphenMinusEqualsSignKeyword_1_0_1() { return cOperatorHyphenMinusEqualsSignKeyword_1_0_1; }
		
		//'='
		public Keyword getOperatorEqualsSignKeyword_1_0_2() { return cOperatorEqualsSignKeyword_1_0_2; }
		
		//value=INT
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_2_0() { return cValueINTTerminalRuleCall_2_0; }
	}
	public class EndNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl.EndNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEndNodeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDisplayTextKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTextAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTextSTRINGTerminalRuleCall_5_0 = (RuleCall)cTextAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//EndNode:
		//    'EndNode' name=ID '{'
		//        'displayText' ':' text=STRING
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'EndNode' name=ID '{'
		//    'displayText' ':' text=STRING
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'EndNode'
		public Keyword getEndNodeKeyword_0() { return cEndNodeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'displayText'
		public Keyword getDisplayTextKeyword_3() { return cDisplayTextKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//text=STRING
		public Assignment getTextAssignment_5() { return cTextAssignment_5; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_5_0() { return cTextSTRINGTerminalRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final StoryElements pStory;
	private final NodeElements pNode;
	private final ChoiceNodeElements pChoiceNode;
	private final ChoiceOptionElements pChoiceOption;
	private final TransitionElements pTransition;
	private final StartNodeElements pStartNode;
	private final DialogueNodeElements pDialogueNode;
	private final ConditionElements pCondition;
	private final OrConditionElements pOrCondition;
	private final AndConditionElements pAndCondition;
	private final PrimaryElements pPrimary;
	private final ComparisonElements pComparison;
	private final OperatorElements pOperator;
	private final SystemStateChangeNodeElements pSystemStateChangeNode;
	private final StateUpdateElements pStateUpdate;
	private final EndNodeElements pEndNode;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public IfictiondslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pStory = new StoryElements();
		this.pNode = new NodeElements();
		this.pChoiceNode = new ChoiceNodeElements();
		this.pChoiceOption = new ChoiceOptionElements();
		this.pTransition = new TransitionElements();
		this.pStartNode = new StartNodeElements();
		this.pDialogueNode = new DialogueNodeElements();
		this.pCondition = new ConditionElements();
		this.pOrCondition = new OrConditionElements();
		this.pAndCondition = new AndConditionElements();
		this.pPrimary = new PrimaryElements();
		this.pComparison = new ComparisonElements();
		this.pOperator = new OperatorElements();
		this.pSystemStateChangeNode = new SystemStateChangeNodeElements();
		this.pStateUpdate = new StateUpdateElements();
		this.pEndNode = new EndNodeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	///*Model:
	//    greetings+=Greeting*;
	//Greeting:
	//    'Hello' name=ID '!';
	// */
	//Story:
	//    'Story' name=ID
	//    (nodes+=Node)*;
	public StoryElements getStoryAccess() {
		return pStory;
	}
	
	public ParserRule getStoryRule() {
		return getStoryAccess().getRule();
	}
	
	//Node:
	//    StartNode | ChoiceNode | DialogueNode | SystemStateChangeNode | EndNode;
	public NodeElements getNodeAccess() {
		return pNode;
	}
	
	public ParserRule getNodeRule() {
		return getNodeAccess().getRule();
	}
	
	//ChoiceNode:
	//    'ChoiceNode' name=ID '{'
	//        'choices' ':' '['
	//            (options+=ChoiceOption (',' options+=ChoiceOption)*)?
	//            ']'
	//        '}';
	public ChoiceNodeElements getChoiceNodeAccess() {
		return pChoiceNode;
	}
	
	public ParserRule getChoiceNodeRule() {
		return getChoiceNodeAccess().getRule();
	}
	
	//ChoiceOption:
	//    'ChoiceOption' '{'
	//        'displayText' ':' text=STRING ','
	//        (transitions+=Transition (',' transitions+=Transition)*)
	//    '}';
	public ChoiceOptionElements getChoiceOptionAccess() {
		return pChoiceOption;
	}
	
	public ParserRule getChoiceOptionRule() {
		return getChoiceOptionAccess().getRule();
	}
	
	//Transition:
	//    '->' destination=[Node]
	//    ('with' 'priority' priority=INT)?
	//    ('with' 'condition' ':' condition=Condition)?;
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//StartNode:
	//        'StartNode' name=ID '{'
	//        'displayText' ':' text=STRING ','
	//        transition=Transition
	//        '}';
	public StartNodeElements getStartNodeAccess() {
		return pStartNode;
	}
	
	public ParserRule getStartNodeRule() {
		return getStartNodeAccess().getRule();
	}
	
	//DialogueNode:
	//        'DialogueNode' name=ID '{'
	//        'displayText' ':' text=STRING ','
	//        transition=Transition
	//        '}';
	public DialogueNodeElements getDialogueNodeAccess() {
		return pDialogueNode;
	}
	
	public ParserRule getDialogueNodeRule() {
		return getDialogueNodeAccess().getRule();
	}
	
	////===================================================
	//Condition: // entry
	//    OrCondition;
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//OrCondition returns Condition: // low priority
	//    AndCondition ({Or.left=current} 'or' right=AndCondition)*;
	public OrConditionElements getOrConditionAccess() {
		return pOrCondition;
	}
	
	public ParserRule getOrConditionRule() {
		return getOrConditionAccess().getRule();
	}
	
	//AndCondition returns Condition: // high priority
	//    // Primary ({And.left=current} 'and' right=Primary)*;
	//    Primary ({And.left=current} 'and' right=Primary)*;
	public AndConditionElements getAndConditionAccess() {
		return pAndCondition;
	}
	
	public ParserRule getAndConditionRule() {
		return getAndConditionAccess().getRule();
	}
	
	//Primary returns Condition:
	//    '(' Condition ')' | Comparison;
	public PrimaryElements getPrimaryAccess() {
		return pPrimary;
	}
	
	public ParserRule getPrimaryRule() {
		return getPrimaryAccess().getRule();
	}
	
	//Comparison:
	//    (variable=ID operator=Operator value=INT);
	public ComparisonElements getComparisonAccess() {
		return pComparison;
	}
	
	public ParserRule getComparisonRule() {
		return getComparisonAccess().getRule();
	}
	
	//Operator: ('='|'!='|'>'|'<'|'>='|'<=');
	public OperatorElements getOperatorAccess() {
		return pOperator;
	}
	
	public ParserRule getOperatorRule() {
		return getOperatorAccess().getRule();
	}
	
	////===================================================
	////Condition:
	//    //(variable= ID Operator value=INT ('and'|'or' conditions+=Condition)*);
	//SystemStateChangeNode:
	//    'SystemStateChangeNode' name=ID '{'
	//    'displayText' ':' text=STRING ','
	//    stateUpdates+=StateUpdate(',' stateUpdates+=StateUpdate)*
	//    transition=Transition
	//    '}';
	public SystemStateChangeNodeElements getSystemStateChangeNodeAccess() {
		return pSystemStateChangeNode;
	}
	
	public ParserRule getSystemStateChangeNodeRule() {
		return getSystemStateChangeNodeAccess().getRule();
	}
	
	//StateUpdate:
	//    (variable=STRING operator=('+='|'-='|'=') value=INT);
	public StateUpdateElements getStateUpdateAccess() {
		return pStateUpdate;
	}
	
	public ParserRule getStateUpdateRule() {
		return getStateUpdateAccess().getRule();
	}
	
	//EndNode:
	//    'EndNode' name=ID '{'
	//        'displayText' ':' text=STRING
	//    '}';
	public EndNodeElements getEndNodeAccess() {
		return pEndNode;
	}
	
	public ParserRule getEndNodeRule() {
		return getEndNodeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
