/**
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IfictiondslValidator extends AbstractIfictiondslValidator {
}
