/*
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IfictiondslRuntimeModule extends AbstractIfictiondslRuntimeModule {
}
