/*
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl;

import com.google.inject.Guice;
import com.google.inject.Injector;
import net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.IfictiondslPackage;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.common.TerminalsStandaloneSetup;
import org.eclipse.xtext.resource.IResourceFactory;
import org.eclipse.xtext.resource.IResourceServiceProvider;

@SuppressWarnings("all")
public class IfictiondslStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		TerminalsStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new IfictiondslRuntimeModule());
	}
	
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.seralyne.net/coursework/mdsd/ifictiondsl/Ifictiondsl")) {
			EPackage.Registry.INSTANCE.put("http://www.seralyne.net/coursework/mdsd/ifictiondsl/Ifictiondsl", IfictiondslPackage.eINSTANCE);
		}
		IResourceFactory resourceFactory = injector.getInstance(IResourceFactory.class);
		IResourceServiceProvider serviceProvider = injector.getInstance(IResourceServiceProvider.class);
		
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("ifiction", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("ifiction", serviceProvider);
	}
}
