/*
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIfictiondslScopeProvider extends DelegatingScopeProvider {
}
