/*
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.parser.antlr;

import com.google.inject.Inject;
import net.seralyne.coursework.mdsd.ifictiondsl.parser.antlr.internal.InternalIfictiondslParser;
import net.seralyne.coursework.mdsd.ifictiondsl.services.IfictiondslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class IfictiondslParser extends AbstractAntlrParser {

	@Inject
	private IfictiondslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIfictiondslParser createParser(XtextTokenStream stream) {
		return new InternalIfictiondslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Story";
	}

	public IfictiondslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IfictiondslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
