/*
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.ui.tests;

import com.google.inject.Injector;
import net.seralyne.coursework.mdsd.ifictiondsl.ui.internal.IfictiondslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IfictiondslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IfictiondslActivator.getInstance().getInjector("net.seralyne.coursework.mdsd.ifictiondsl.Ifictiondsl");
	}

}
