/*
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.ui;

import com.google.inject.Injector;
import net.seralyne.coursework.mdsd.ifictiondsl.ui.internal.IfictiondslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IfictiondslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(IfictiondslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		IfictiondslActivator activator = IfictiondslActivator.getInstance();
		return activator != null ? activator.getInjector(IfictiondslActivator.NET_SERALYNE_COURSEWORK_MDSD_IFICTIONDSL_IFICTIONDSL) : null;
	}

}
