/*
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceNode;
import net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceOption;
import net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Condition;
import net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.DialogueNode;
import net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.EndNode;
import net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.IfictiondslPackage;
import net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StartNode;
import net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Story;
import net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode;
import net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Transition;
import net.seralyne.coursework.mdsd.ifictiondsl.services.IfictiondslGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class IfictiondslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private IfictiondslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == IfictiondslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case IfictiondslPackage.CHOICE_NODE:
				sequence_ChoiceNode(context, (ChoiceNode) semanticObject); 
				return; 
			case IfictiondslPackage.CHOICE_OPTION:
				sequence_ChoiceOption(context, (ChoiceOption) semanticObject); 
				return; 
			case IfictiondslPackage.CONDITION:
				sequence_Condition(context, (Condition) semanticObject); 
				return; 
			case IfictiondslPackage.DIALOGUE_NODE:
				sequence_DialogueNode(context, (DialogueNode) semanticObject); 
				return; 
			case IfictiondslPackage.END_NODE:
				sequence_EndNode(context, (EndNode) semanticObject); 
				return; 
			case IfictiondslPackage.START_NODE:
				sequence_StartNode(context, (StartNode) semanticObject); 
				return; 
			case IfictiondslPackage.STORY:
				sequence_Story(context, (Story) semanticObject); 
				return; 
			case IfictiondslPackage.SYSTEM_STATE_CHANGE_NODE:
				sequence_SystemStateChangeNode(context, (SystemStateChangeNode) semanticObject); 
				return; 
			case IfictiondslPackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Node returns ChoiceNode
	 *     ChoiceNode returns ChoiceNode
	 *
	 * Constraint:
	 *     (name=ID (options+=ChoiceOption options+=ChoiceOption*)?)
	 * </pre>
	 */
	protected void sequence_ChoiceNode(ISerializationContext context, ChoiceNode semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ChoiceOption returns ChoiceOption
	 *
	 * Constraint:
	 *     (text=STRING transitions+=Transition transitions+=Transition*)
	 * </pre>
	 */
	protected void sequence_ChoiceOption(ISerializationContext context, ChoiceOption semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Condition returns Condition
	 *
	 * Constraint:
	 *     (variable=ID (operator='=' | operator='!=' | operator='&gt;' | operator='&lt;') value=INT)
	 * </pre>
	 */
	protected void sequence_Condition(ISerializationContext context, Condition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Node returns DialogueNode
	 *     DialogueNode returns DialogueNode
	 *
	 * Constraint:
	 *     (name=ID text=STRING transition=Transition)
	 * </pre>
	 */
	protected void sequence_DialogueNode(ISerializationContext context, DialogueNode semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IfictiondslPackage.Literals.NODE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IfictiondslPackage.Literals.NODE__NAME));
			if (transientValues.isValueTransient(semanticObject, IfictiondslPackage.Literals.DIALOGUE_NODE__TEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IfictiondslPackage.Literals.DIALOGUE_NODE__TEXT));
			if (transientValues.isValueTransient(semanticObject, IfictiondslPackage.Literals.DIALOGUE_NODE__TRANSITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IfictiondslPackage.Literals.DIALOGUE_NODE__TRANSITION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDialogueNodeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getDialogueNodeAccess().getTextSTRINGTerminalRuleCall_5_0(), semanticObject.getText());
		feeder.accept(grammarAccess.getDialogueNodeAccess().getTransitionTransitionParserRuleCall_7_0(), semanticObject.getTransition());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Node returns EndNode
	 *     EndNode returns EndNode
	 *
	 * Constraint:
	 *     (name=ID text=STRING)
	 * </pre>
	 */
	protected void sequence_EndNode(ISerializationContext context, EndNode semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IfictiondslPackage.Literals.NODE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IfictiondslPackage.Literals.NODE__NAME));
			if (transientValues.isValueTransient(semanticObject, IfictiondslPackage.Literals.END_NODE__TEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IfictiondslPackage.Literals.END_NODE__TEXT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEndNodeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getEndNodeAccess().getTextSTRINGTerminalRuleCall_5_0(), semanticObject.getText());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Node returns StartNode
	 *     StartNode returns StartNode
	 *
	 * Constraint:
	 *     (name=ID text=STRING transition=Transition)
	 * </pre>
	 */
	protected void sequence_StartNode(ISerializationContext context, StartNode semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IfictiondslPackage.Literals.NODE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IfictiondslPackage.Literals.NODE__NAME));
			if (transientValues.isValueTransient(semanticObject, IfictiondslPackage.Literals.START_NODE__TEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IfictiondslPackage.Literals.START_NODE__TEXT));
			if (transientValues.isValueTransient(semanticObject, IfictiondslPackage.Literals.START_NODE__TRANSITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IfictiondslPackage.Literals.START_NODE__TRANSITION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStartNodeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getStartNodeAccess().getTextSTRINGTerminalRuleCall_5_0(), semanticObject.getText());
		feeder.accept(grammarAccess.getStartNodeAccess().getTransitionTransitionParserRuleCall_7_0(), semanticObject.getTransition());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Story returns Story
	 *
	 * Constraint:
	 *     (name=ID nodes+=Node*)
	 * </pre>
	 */
	protected void sequence_Story(ISerializationContext context, Story semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Node returns SystemStateChangeNode
	 *     SystemStateChangeNode returns SystemStateChangeNode
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         text=STRING 
	 *         variable=STRING 
	 *         (operator='+=' | operator='-=' | operator='=') 
	 *         value=INT 
	 *         transition=Transition
	 *     )
	 * </pre>
	 */
	protected void sequence_SystemStateChangeNode(ISerializationContext context, SystemStateChangeNode semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Transition returns Transition
	 *
	 * Constraint:
	 *     (destination=[Node|ID] priority=INT? condition=Condition?)
	 * </pre>
	 */
	protected void sequence_Transition(ISerializationContext context, Transition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
