/*
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import net.seralyne.coursework.mdsd.ifictiondsl.ide.contentassist.antlr.internal.InternalIfictiondslParser;
import net.seralyne.coursework.mdsd.ifictiondsl.services.IfictiondslGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class IfictiondslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(IfictiondslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, IfictiondslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getNodeAccess().getAlternatives(), "rule__Node__Alternatives");
			builder.put(grammarAccess.getConditionAccess().getOperatorAlternatives_1_0(), "rule__Condition__OperatorAlternatives_1_0");
			builder.put(grammarAccess.getSystemStateChangeNodeAccess().getOperatorAlternatives_8_0(), "rule__SystemStateChangeNode__OperatorAlternatives_8_0");
			builder.put(grammarAccess.getStoryAccess().getGroup(), "rule__Story__Group__0");
			builder.put(grammarAccess.getChoiceNodeAccess().getGroup(), "rule__ChoiceNode__Group__0");
			builder.put(grammarAccess.getChoiceNodeAccess().getGroup_6(), "rule__ChoiceNode__Group_6__0");
			builder.put(grammarAccess.getChoiceNodeAccess().getGroup_6_1(), "rule__ChoiceNode__Group_6_1__0");
			builder.put(grammarAccess.getChoiceOptionAccess().getGroup(), "rule__ChoiceOption__Group__0");
			builder.put(grammarAccess.getChoiceOptionAccess().getGroup_6(), "rule__ChoiceOption__Group_6__0");
			builder.put(grammarAccess.getChoiceOptionAccess().getGroup_6_1(), "rule__ChoiceOption__Group_6_1__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_2(), "rule__Transition__Group_2__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_3(), "rule__Transition__Group_3__0");
			builder.put(grammarAccess.getStartNodeAccess().getGroup(), "rule__StartNode__Group__0");
			builder.put(grammarAccess.getDialogueNodeAccess().getGroup(), "rule__DialogueNode__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
			builder.put(grammarAccess.getSystemStateChangeNodeAccess().getGroup(), "rule__SystemStateChangeNode__Group__0");
			builder.put(grammarAccess.getEndNodeAccess().getGroup(), "rule__EndNode__Group__0");
			builder.put(grammarAccess.getStoryAccess().getNameAssignment_1(), "rule__Story__NameAssignment_1");
			builder.put(grammarAccess.getStoryAccess().getNodesAssignment_2(), "rule__Story__NodesAssignment_2");
			builder.put(grammarAccess.getChoiceNodeAccess().getNameAssignment_1(), "rule__ChoiceNode__NameAssignment_1");
			builder.put(grammarAccess.getChoiceNodeAccess().getOptionsAssignment_6_0(), "rule__ChoiceNode__OptionsAssignment_6_0");
			builder.put(grammarAccess.getChoiceNodeAccess().getOptionsAssignment_6_1_1(), "rule__ChoiceNode__OptionsAssignment_6_1_1");
			builder.put(grammarAccess.getChoiceOptionAccess().getTextAssignment_4(), "rule__ChoiceOption__TextAssignment_4");
			builder.put(grammarAccess.getChoiceOptionAccess().getTransitionsAssignment_6_0(), "rule__ChoiceOption__TransitionsAssignment_6_0");
			builder.put(grammarAccess.getChoiceOptionAccess().getTransitionsAssignment_6_1_1(), "rule__ChoiceOption__TransitionsAssignment_6_1_1");
			builder.put(grammarAccess.getTransitionAccess().getDestinationAssignment_1(), "rule__Transition__DestinationAssignment_1");
			builder.put(grammarAccess.getTransitionAccess().getPriorityAssignment_2_2(), "rule__Transition__PriorityAssignment_2_2");
			builder.put(grammarAccess.getTransitionAccess().getConditionAssignment_3_3(), "rule__Transition__ConditionAssignment_3_3");
			builder.put(grammarAccess.getStartNodeAccess().getNameAssignment_1(), "rule__StartNode__NameAssignment_1");
			builder.put(grammarAccess.getStartNodeAccess().getTextAssignment_5(), "rule__StartNode__TextAssignment_5");
			builder.put(grammarAccess.getStartNodeAccess().getTransitionAssignment_7(), "rule__StartNode__TransitionAssignment_7");
			builder.put(grammarAccess.getDialogueNodeAccess().getNameAssignment_1(), "rule__DialogueNode__NameAssignment_1");
			builder.put(grammarAccess.getDialogueNodeAccess().getTextAssignment_5(), "rule__DialogueNode__TextAssignment_5");
			builder.put(grammarAccess.getDialogueNodeAccess().getTransitionAssignment_7(), "rule__DialogueNode__TransitionAssignment_7");
			builder.put(grammarAccess.getConditionAccess().getVariableAssignment_0(), "rule__Condition__VariableAssignment_0");
			builder.put(grammarAccess.getConditionAccess().getOperatorAssignment_1(), "rule__Condition__OperatorAssignment_1");
			builder.put(grammarAccess.getConditionAccess().getValueAssignment_2(), "rule__Condition__ValueAssignment_2");
			builder.put(grammarAccess.getSystemStateChangeNodeAccess().getNameAssignment_1(), "rule__SystemStateChangeNode__NameAssignment_1");
			builder.put(grammarAccess.getSystemStateChangeNodeAccess().getTextAssignment_5(), "rule__SystemStateChangeNode__TextAssignment_5");
			builder.put(grammarAccess.getSystemStateChangeNodeAccess().getVariableAssignment_7(), "rule__SystemStateChangeNode__VariableAssignment_7");
			builder.put(grammarAccess.getSystemStateChangeNodeAccess().getOperatorAssignment_8(), "rule__SystemStateChangeNode__OperatorAssignment_8");
			builder.put(grammarAccess.getSystemStateChangeNodeAccess().getValueAssignment_9(), "rule__SystemStateChangeNode__ValueAssignment_9");
			builder.put(grammarAccess.getSystemStateChangeNodeAccess().getTransitionAssignment_11(), "rule__SystemStateChangeNode__TransitionAssignment_11");
			builder.put(grammarAccess.getEndNodeAccess().getNameAssignment_1(), "rule__EndNode__NameAssignment_1");
			builder.put(grammarAccess.getEndNodeAccess().getTextAssignment_5(), "rule__EndNode__TextAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private IfictiondslGrammarAccess grammarAccess;

	@Override
	protected InternalIfictiondslParser createParser() {
		InternalIfictiondslParser result = new InternalIfictiondslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public IfictiondslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IfictiondslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
