/**
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import net.mudcrab.coursework.mbsd.IfictiondslRuntimeModule;
import net.mudcrab.coursework.mbsd.IfictiondslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class IfictiondslIdeSetup extends IfictiondslStandaloneSetup {
  @Override
  public Injector createInjector() {
    IfictiondslRuntimeModule _ifictiondslRuntimeModule = new IfictiondslRuntimeModule();
    IfictiondslIdeModule _ifictiondslIdeModule = new IfictiondslIdeModule();
    return Guice.createInjector(Modules2.mixin(_ifictiondslRuntimeModule, _ifictiondslIdeModule));
  }
}
