/**
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IfictiondslIdeModule extends AbstractIfictiondslIdeModule {
}
