/**
 * generated by Xtext 2.42.0
 */
package net.mudcrab.coursework.mbsd.validation;

import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.function.Predicate;
import net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceNode;
import net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption;
import net.mudcrab.coursework.mbsd.ifictiondsl.Comparison;
import net.mudcrab.coursework.mbsd.ifictiondsl.Condition;
import net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage;
import net.mudcrab.coursework.mbsd.ifictiondsl.Node;
import net.mudcrab.coursework.mbsd.ifictiondsl.Parentheses;
import net.mudcrab.coursework.mbsd.ifictiondsl.StateUpdate;
import net.mudcrab.coursework.mbsd.ifictiondsl.Story;
import net.mudcrab.coursework.mbsd.ifictiondsl.SystemStateChangeNode;
import net.mudcrab.coursework.mbsd.ifictiondsl.Transition;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IfictiondslValidator extends AbstractIfictiondslValidator {
  public static final String NOT_REFERENCED_BY_TRANSITION = "notReferencedByTransition";

  public static final String NODE_TRANSITIONS_TO_ITSELF = "nodeTransitionsToItself";

  public static final String NODE_IS_UNREACHABLE = "nodeIsUnreachable";

  public static final String TRANSITION_CONDITION_CANNOT_BE_SATISFIED = "transitionConditionCannotBeSatisfied";

  @Check(CheckType.FAST)
  public void checkNotRefferencedByAnyTransitions(final Node node) {
    int _size = EcoreUtil.UsageCrossReferencer.find(node, node.eContainer()).size();
    boolean _tripleEquals = (_size == 0);
    if (_tripleEquals) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Node with name \'");
      String _name = node.getName();
      _builder.append(_name);
      _builder.append("\' is not referenced by any transitions in story");
      this.warning(_builder.toString(), 
        IfictiondslPackage.Literals.NODE__NAME, 
        IfictiondslValidator.NOT_REFERENCED_BY_TRANSITION);
    }
  }

  @Check(CheckType.FAST)
  public void checkNotTransitioningToItself(final Node node) {
    boolean _matched = false;
    if (node instanceof ChoiceNode) {
      _matched=true;
      EList<ChoiceOption> _options = ((ChoiceNode)node).getOptions();
      for (final ChoiceOption option : _options) {
        EList<Transition> _transitions = option.getTransitions();
        for (final Transition transition : _transitions) {
          Node _destination = transition.getDestination();
          boolean _tripleEquals = (_destination == node);
          if (_tripleEquals) {
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("ChoiceOption is transitioning to own ChoiceNode");
            this.error(_builder.toString(), transition, 
              IfictiondslPackage.Literals.TRANSITION__DESTINATION, 
              IfictiondslValidator.NODE_TRANSITIONS_TO_ITSELF);
          }
        }
      }
    }
    if (!_matched) {
      {
        final EStructuralFeature structuralFeature = node.eClass().getEStructuralFeature("transition");
        if ((structuralFeature != null)) {
          Object _eGet = node.eGet(structuralFeature);
          final Transition transition = ((Transition) _eGet);
          Node _destination = transition.getDestination();
          boolean _tripleEquals = (_destination == node);
          if (_tripleEquals) {
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("Node is transitioning to itself");
            this.error(_builder.toString(), transition, 
              IfictiondslPackage.Literals.TRANSITION__DESTINATION, 
              IfictiondslValidator.NODE_TRANSITIONS_TO_ITSELF);
          }
        }
      }
    }
  }

  @Check(CheckType.NORMAL)
  public void checkDetectDeadLeaves(final Story story) {
    final ASTTraverser traverser = new ASTTraverser();
    traverser.traverseStory(story);
    final List<Transition> allTransitions = EcoreUtil2.<Transition>getAllContentsOfType(story, Transition.class);
    HashSet<Node> deadNodeCandidates = new HashSet<Node>();
    EList<Node> _nodes = story.getNodes();
    for (final Node node : _nodes) {
      boolean _containsKey = traverser.getVisitedNodes().containsKey(node);
      boolean _not = (!_containsKey);
      if (_not) {
        deadNodeCandidates.add(node);
      }
    }
    HashSet<Node> _nodesNotRefferencedByAnyTransitions = this.getNodesNotRefferencedByAnyTransitions(story, allTransitions);
    for (final Node notRefedNode : _nodesNotRefferencedByAnyTransitions) {
      deadNodeCandidates.remove(notRefedNode);
    }
    HashSet<Transition> transitionCandidates = new HashSet<Transition>();
    HashSet<Node> furtherDownTheDeadBranchNodes = new HashSet<Node>();
    Object[] _array = deadNodeCandidates.toArray();
    for (final Object deadNodeCand : _array) {
      {
        boolean keep = false;
        for (final Transition transition : allTransitions) {
          Node _destination = transition.getDestination();
          boolean _tripleEquals = (_destination == deadNodeCand);
          if (_tripleEquals) {
            EObject container = transition.eContainer();
            if ((container instanceof ChoiceOption)) {
              container = ((ChoiceOption)container).eContainer();
            }
            boolean _containsKey_1 = traverser.getVisitedNodes().containsKey(container);
            if (_containsKey_1) {
              transitionCandidates.add(transition);
              keep = true;
            }
          }
        }
        if ((!keep)) {
          keep = false;
          deadNodeCandidates.remove(deadNodeCand);
          furtherDownTheDeadBranchNodes.add(((Node) deadNodeCand));
        }
      }
    }
    int deadNodeCandidateCount = 0;
    do {
      {
        final HashSet<Node> _converted_deadNodeCandidates = (HashSet<Node>)deadNodeCandidates;
        deadNodeCandidateCount = ((Object[])Conversions.unwrapArray(_converted_deadNodeCandidates, Object.class)).length;
        for (final Transition transCand : transitionCandidates) {
          {
            HashMap<Node, TraversalNode> _visitedNodes = traverser.getVisitedNodes();
            final Function1<TraversalNode, Boolean> _function = (TraversalNode it) -> {
              return Boolean.valueOf(ASTTraverser.checkCondition(transCand.getCondition(), it.getStateSnapshot()));
            };
            final Iterable<TraversalNode> travNodesWithRightState = IterableExtensions.<TraversalNode>filter(new HashMap<Node, TraversalNode>(_visitedNodes).values(), _function);
            for (final TraversalNode travNode : travNodesWithRightState) {
              if (((travNode != null) && 
                traverser.findNodeFrom(travNode.getNode(), transCand.getDestination()))) {
              }
            }
          }
        }
        Object[] _array_1 = deadNodeCandidates.toArray();
        for (final Object deadNodeCand_1 : _array_1) {
          boolean _containsKey_1 = traverser.getVisitedNodes().containsKey(deadNodeCand_1);
          if (_containsKey_1) {
            deadNodeCandidates.remove(deadNodeCand_1);
            final Predicate<Transition> _function = (Transition it) -> {
              return it.getDestination().equals(deadNodeCand_1);
            };
            transitionCandidates.removeIf(_function);
          }
        }
      }
    } while((deadNodeCandidateCount > ((Object[])Conversions.unwrapArray(deadNodeCandidates, Object.class)).length));
    final Function1<Transition, Integer> _function = (Transition it) -> {
      int _priority = it.getPriority();
      return Integer.valueOf((-_priority));
    };
    final List<Transition> transCandidatedsSortedByPriority = IterableExtensions.<Transition, Integer>sortBy(transitionCandidates, _function);
    for (final Transition transCand : transCandidatedsSortedByPriority) {
    }
    for (final Transition transCand_1 : transCandidatedsSortedByPriority) {
      boolean _analyseConditionAndTryToFulfillItByTraversingAST = this.analyseConditionAndTryToFulfillItByTraversingAST(transCand_1.getCondition(), traverser);
      if (_analyseConditionAndTryToFulfillItByTraversingAST) {
        final Function1<TraversalNode, Boolean> _function_1 = (TraversalNode node_1) -> {
          return Boolean.valueOf(ASTTraverser.checkCondition(
            transCand_1.getCondition(), 
            node_1.getStateSnapshot()));
        };
        TraversalNode nodeWithRightStateToGetToDeadNodeCandidate = IterableExtensions.<TraversalNode>findFirst(traverser.getVisitedNodes().values(), _function_1);
        if (((nodeWithRightStateToGetToDeadNodeCandidate != null) && 
          traverser.findNodeFrom(nodeWithRightStateToGetToDeadNodeCandidate.getNode(), transCand_1.getDestination(), true))) {
        } else {
        }
      } else {
      }
    }
    Object[] _array_1 = deadNodeCandidates.toArray();
    for (final Object deadNodeCand_1 : _array_1) {
      boolean _containsKey_1 = traverser.getVisitedNodes().containsKey(deadNodeCand_1);
      if (_containsKey_1) {
        deadNodeCandidates.remove(deadNodeCand_1);
        final Predicate<Transition> _function_2 = (Transition it) -> {
          return it.getDestination().equals(deadNodeCand_1);
        };
        transCandidatedsSortedByPriority.removeIf(_function_2);
      }
    }
    for (final Node deadNode : deadNodeCandidates) {
      {
        this.warning("Node is unreachable. Condition cannot be satisfied", deadNode, 
          null, 
          IfictiondslValidator.NODE_IS_UNREACHABLE);
        for (final Transition transCand_2 : transCandidatedsSortedByPriority) {
          Node _destination = transCand_2.getDestination();
          boolean _tripleEquals = (_destination == deadNode);
          if (_tripleEquals) {
            this.warning("Transition condition cannot be satisfied from traversing the story and destination node is therefore unreachable", transCand_2, 
              IfictiondslPackage.Literals.TRANSITION__CONDITION, 
              IfictiondslValidator.TRANSITION_CONDITION_CANNOT_BE_SATISFIED);
          }
        }
        this.putWarningsOnDeadNodesDownDeadBranch(deadNode, traverser);
      }
    }
    System.out.println("Got here final");
  }

  private void putWarningsOnDeadNodesDownDeadBranch(final Node deadNode, final ASTTraverser traverser) {
    boolean _matched = false;
    if (deadNode instanceof ChoiceNode) {
      _matched=true;
      EList<ChoiceOption> _options = ((ChoiceNode)deadNode).getOptions();
      for (final ChoiceOption option : _options) {
        EList<Transition> _transitions = option.getTransitions();
        for (final Transition transition : _transitions) {
          boolean _containsKey = traverser.getVisitedNodes().containsKey(transition.getDestination());
          boolean _not = (!_containsKey);
          if (_not) {
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("Node is unreachable because parent node: ");
            _builder.append(((ChoiceNode)deadNode));
            _builder.append(" is unreachable.");
            this.warning(_builder.toString(), 
              transition.getDestination(), 
              null, 
              IfictiondslValidator.NODE_IS_UNREACHABLE);
            this.putWarningsOnDeadNodesDownDeadBranch(transition.getDestination(), traverser);
          }
        }
      }
    }
    if (!_matched) {
      {
        final EStructuralFeature structuralFeature = deadNode.eClass().getEStructuralFeature("transition");
        if ((structuralFeature != null)) {
          Object _eGet = deadNode.eGet(structuralFeature);
          final Transition transition = ((Transition) _eGet);
          if (((transition != null) && (!traverser.getVisitedNodes().containsKey(transition.getDestination())))) {
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("Node is unreachable because parent node: ");
            _builder.append(deadNode);
            _builder.append(" is unreachable.");
            this.warning(_builder.toString(), 
              transition.getDestination(), 
              null, 
              IfictiondslValidator.NODE_IS_UNREACHABLE);
            this.putWarningsOnDeadNodesDownDeadBranch(transition.getDestination(), traverser);
          }
        }
      }
    }
  }

  private boolean analyseConditionAndTryToFulfillItByTraversingAST(final Condition condition, final ASTTraverser traverser) {
    final TraversalCondition travCond = new TraversalCondition(condition);
    boolean isConditionFulfillable = true;
    while ((isConditionFulfillable && travCond.buildNextComparisonChain())) {
      {
        final Function1<Condition, Boolean> _function = (Condition comp) -> {
          boolean _matched = false;
          if (comp instanceof Comparison) {
            _matched=true;
            boolean _checkIfComparisonIsAchievedByAnyVisitedNode = this.checkIfComparisonIsAchievedByAnyVisitedNode(((Comparison)comp), traverser);
            boolean _not = (!_checkIfComparisonIsAchievedByAnyVisitedNode);
            if (_not) {
              final Iterable<SystemStateChangeNode> scnodes = this.getVisitedStateChangeNodesThatCanHelpAchieveComparison(((Comparison)comp), traverser);
              int _size = IterableExtensions.size(scnodes);
              boolean _tripleEquals = (_size == 0);
              if (_tripleEquals) {
                return Boolean.valueOf(true);
              }
              for (final SystemStateChangeNode scnode : scnodes) {
                {
                  final Function1<Transition, Boolean> _function_1 = (Transition trans) -> {
                    Node _destination = trans.getDestination();
                    return Boolean.valueOf((_destination == scnode));
                  };
                  final Transition transitionToScnode = IterableExtensions.<Transition>findFirst(traverser.getVisitedTransitions(), _function_1);
                  final Function1<TraversalNode, Boolean> _function_2 = (TraversalNode node) -> {
                    return Boolean.valueOf(ASTTraverser.checkCondition(
                      transitionToScnode.getCondition(), 
                      node.getStateSnapshot()));
                  };
                  Node nodeWithRightStateToGetToScnode = IterableExtensions.<TraversalNode>findFirst(traverser.getVisitedNodes().values(), _function_2).getNode();
                  while (((!this.checkIfComparisonIsAchievedByAnyVisitedNode(((Comparison)comp), traverser)) && traverser.findNodeFrom(nodeWithRightStateToGetToScnode, scnode, 
                    true))) {
                    nodeWithRightStateToGetToScnode = scnode;
                  }
                  boolean _checkIfComparisonIsAchievedByAnyVisitedNode_1 = this.checkIfComparisonIsAchievedByAnyVisitedNode(((Comparison)comp), traverser);
                  if (_checkIfComparisonIsAchievedByAnyVisitedNode_1) {
                    return Boolean.valueOf(false);
                  }
                }
              }
              return Boolean.valueOf(true);
            } else {
              return Boolean.valueOf(false);
            }
          }
          if (!_matched) {
            if (comp instanceof Parentheses) {
              _matched=true;
              return Boolean.valueOf(this.analyseConditionAndTryToFulfillItByTraversingAST(((Parentheses)comp).getInner(), traverser));
            }
          }
          System.out.println("We should not be able to get here");
          return Boolean.valueOf(false);
        };
        final Condition firstFailedComparison = IterableExtensions.<Condition>findFirst(travCond.getComparisonChain(), _function);
        isConditionFulfillable = (firstFailedComparison == null);
      }
    }
    return isConditionFulfillable;
  }

  private boolean checkIfComparisonIsAchievedByAnyVisitedNode(final Comparison comp, final ASTTraverser traverser) {
    Collection<TraversalNode> _values = traverser.getVisitedNodes().values();
    for (final TraversalNode travNode : _values) {
      boolean _containsKey = travNode.getStateSnapshot().containsKey(comp.getVariable());
      if (_containsKey) {
        boolean _checkCondition = ASTTraverser.checkCondition(comp, travNode.getStateSnapshot());
        if (_checkCondition) {
          return true;
        }
      }
    }
    return false;
  }

  private Iterable<SystemStateChangeNode> getVisitedStateChangeNodesThatCanHelpAchieveComparison(final Comparison comp, final ASTTraverser traverser) {
    final Function1<SystemStateChangeNode, Boolean> _function = (SystemStateChangeNode scnode) -> {
      EList<StateUpdate> _stateUpdates = scnode.getStateUpdates();
      for (final StateUpdate stateUpdate : _stateUpdates) {
        boolean _equals = stateUpdate.getVariable().equals(comp.getVariable());
        if (_equals) {
          boolean _equals_1 = "=".equals(stateUpdate.getOperator());
          if (_equals_1) {
            boolean _contains = "<= >= ==".contains(comp.getOperator());
            if (_contains) {
              int _value = stateUpdate.getValue();
              int _value_1 = comp.getValue();
              return Boolean.valueOf((_value == _value_1));
            } else {
              return Boolean.valueOf(false);
            }
          } else {
            boolean _contains_1 = "< <=".contains(comp.getOperator());
            if (_contains_1) {
              return Boolean.valueOf("-=".equals(stateUpdate.getOperator()));
            }
            boolean _contains_2 = "> >=".contains(comp.getOperator());
            if (_contains_2) {
              return Boolean.valueOf("+=".equals(stateUpdate.getOperator()));
            }
            boolean _equals_2 = "==".equals(comp.getOperator());
            if (_equals_2) {
              Collection<TraversalNode> _values = traverser.getVisitedNodes().values();
              for (final TraversalNode travNode : _values) {
                {
                  final Integer current = travNode.getStateSnapshot().getOrDefault(comp.getVariable(), Integer.valueOf(0));
                  int _value_2 = comp.getValue();
                  int _minus = ((current).intValue() - _value_2);
                  int _value_3 = stateUpdate.getValue();
                  int _modulo = (_minus % _value_3);
                  boolean _equals_3 = (_modulo == 0);
                  if (_equals_3) {
                    if ((Objects.equals(stateUpdate.getOperator(), "-=") && (((current).intValue() - stateUpdate.getValue()) >= comp.getValue()))) {
                      return Boolean.valueOf(true);
                    }
                    if ((Objects.equals(stateUpdate.getOperator(), "+=") && (((current).intValue() + stateUpdate.getValue()) <= comp.getValue()))) {
                      return Boolean.valueOf(true);
                    }
                  }
                }
              }
              return Boolean.valueOf(false);
            }
          }
        }
      }
      return Boolean.valueOf(false);
    };
    return IterableExtensions.<SystemStateChangeNode>filter(traverser.getVisitedStateChangeNodes(), _function);
  }

  private HashSet<Node> getNodesNotRefferencedByAnyTransitions(final Story story, final List<Transition> allTransitions) {
    EList<Node> _nodes = story.getNodes();
    HashSet<Node> notRefferencedByTransitions = new HashSet<Node>(_nodes);
    for (final Transition t : allTransitions) {
      boolean _contains = notRefferencedByTransitions.contains(t.getDestination());
      if (_contains) {
        notRefferencedByTransitions.remove(t.getDestination());
      }
    }
    return notRefferencedByTransitions;
  }
}
