/**
 * generated by Xtext 2.42.0
 */
package net.mudcrab.coursework.mbsd.validation;

import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption;
import net.mudcrab.coursework.mbsd.ifictiondsl.Comparison;
import net.mudcrab.coursework.mbsd.ifictiondsl.Condition;
import net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage;
import net.mudcrab.coursework.mbsd.ifictiondsl.Node;
import net.mudcrab.coursework.mbsd.ifictiondsl.Parentheses;
import net.mudcrab.coursework.mbsd.ifictiondsl.StateUpdate;
import net.mudcrab.coursework.mbsd.ifictiondsl.Story;
import net.mudcrab.coursework.mbsd.ifictiondsl.SystemStateChangeNode;
import net.mudcrab.coursework.mbsd.ifictiondsl.Transition;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IfictiondslValidator extends AbstractIfictiondslValidator {
  public static final String NOT_REFERENCED_BY_TRANSITION = "notReferencedByTransition";

  @Check(CheckType.FAST)
  public void checkNotRefferencedByAnyTransitions(final Node node) {
    System.out.println("checkNotRefferencedByAnyTransitions called");
    int _size = EcoreUtil.UsageCrossReferencer.find(node, node.eContainer()).size();
    boolean _tripleEquals = (_size == 0);
    if (_tripleEquals) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Node with name \'");
      String _name = node.getName();
      _builder.append(_name);
      _builder.append("\' is not referenced by any transitions!");
      this.warning(_builder.toString(), 
        IfictiondslPackage.Literals.NODE__NAME, 
        IfictiondslValidator.NOT_REFERENCED_BY_TRANSITION);
    }
  }

  @Check(CheckType.NORMAL)
  public void checkDetectDeadLeaves(final Story story) {
    System.out.println("checkDetectDeadLeaves called");
    final ASTTraverser traverser = new ASTTraverser();
    traverser.traverseStory(story);
    final List<Transition> allTransitions = EcoreUtil2.<Transition>getAllContentsOfType(story, Transition.class);
    HashSet<Node> deadNodeCandidates = new HashSet<Node>();
    EList<Node> _nodes = story.getNodes();
    for (final Node node : _nodes) {
      boolean _containsKey = traverser.getVisitedNodes().containsKey(node);
      boolean _not = (!_containsKey);
      if (_not) {
        deadNodeCandidates.add(node);
      }
    }
    HashSet<Node> _nodesNotRefferencedByAnyTransitions = this.getNodesNotRefferencedByAnyTransitions(story, allTransitions);
    for (final Node notRefedNode : _nodesNotRefferencedByAnyTransitions) {
      deadNodeCandidates.remove(notRefedNode);
    }
    HashSet<Transition> transitionCandidates = new HashSet<Transition>();
    Object[] _array = deadNodeCandidates.toArray();
    for (final Object deadNodeCand : _array) {
      {
        boolean keep = false;
        for (final Transition transition : allTransitions) {
          Node _destination = transition.getDestination();
          boolean _tripleEquals = (_destination == deadNodeCand);
          if (_tripleEquals) {
            EObject container = transition.eContainer();
            if ((container instanceof ChoiceOption)) {
              container = ((ChoiceOption)container).eContainer();
            }
            boolean _containsKey_1 = traverser.getVisitedNodes().containsKey(container);
            if (_containsKey_1) {
              transitionCandidates.add(transition);
              keep = true;
            }
          }
        }
        if ((!keep)) {
          keep = false;
          deadNodeCandidates.remove(deadNodeCand);
        }
      }
    }
    int deadNodeCandidateCount = 0;
    do {
      {
        final HashSet<Node> _converted_deadNodeCandidates = (HashSet<Node>)deadNodeCandidates;
        deadNodeCandidateCount = ((Object[])Conversions.unwrapArray(_converted_deadNodeCandidates, Object.class)).length;
        for (final Transition transCand : transitionCandidates) {
          {
            HashMap<Node, TraversalNode> _visitedNodes = traverser.getVisitedNodes();
            final Function1<TraversalNode, Boolean> _function = (TraversalNode it) -> {
              return Boolean.valueOf(ASTTraverser.checkCondition(transCand.getCondition(), it.getStateSnapshot()));
            };
            final Iterable<TraversalNode> travNodesWithRightState = IterableExtensions.<TraversalNode>filter(new HashMap<Node, TraversalNode>(_visitedNodes).values(), _function);
            for (final TraversalNode travNode : travNodesWithRightState) {
              if (((travNode != null) && 
                traverser.findNodeFrom(travNode.getNode(), transCand.getDestination()))) {
                System.out.println("Found at least one new node");
              }
            }
          }
        }
        Object[] _array_1 = deadNodeCandidates.toArray();
        for (final Object deadNodeCand_1 : _array_1) {
          boolean _containsKey_1 = traverser.getVisitedNodes().containsKey(deadNodeCand_1);
          if (_containsKey_1) {
            String _name = ((Node) deadNodeCand_1).getName();
            String _plus = ("Removed a node from candidates: " + _name);
            System.out.println(_plus);
            deadNodeCandidates.remove(deadNodeCand_1);
            final Function1<Transition, Boolean> _function = (Transition it) -> {
              return Boolean.valueOf(it.getDestination().equals(deadNodeCand_1));
            };
            transitionCandidates.remove(
              IterableExtensions.<Transition>findFirst(transitionCandidates, _function));
          }
        }
      }
    } while((deadNodeCandidateCount > ((Object[])Conversions.unwrapArray(deadNodeCandidates, Object.class)).length));
    System.out.println("Got here 1");
    final Function1<Transition, Integer> _function = (Transition it) -> {
      int _priority = it.getPriority();
      return Integer.valueOf((-_priority));
    };
    final List<Transition> transCandidatedsSortedByPriority = IterableExtensions.<Transition, Integer>sortBy(transitionCandidates, _function);
    for (final Transition transCand : transCandidatedsSortedByPriority) {
      boolean _analyseConditionAndTryToFulfillItByTraversingAST = this.analyseConditionAndTryToFulfillItByTraversingAST(transCand.getCondition(), traverser);
      if (_analyseConditionAndTryToFulfillItByTraversingAST) {
        System.out.println("Condition was fulfilled");
      }
    }
    System.out.println("Got here final");
  }

  private boolean analyseConditionAndTryToFulfillItByTraversingAST(final Condition condition, final ASTTraverser traverser) {
    EObject _eContainer = condition.eContainer();
    boolean _not = (!(_eContainer instanceof Condition));
    if (_not) {
      final Function1<TraversalNode, Boolean> _function = (TraversalNode it) -> {
        return Boolean.valueOf(ASTTraverser.checkCondition(condition, it.getStateSnapshot()));
      };
      final Iterable<TraversalNode> travNodesWithRightState = IterableExtensions.<TraversalNode>filter(traverser.getVisitedNodes().values(), _function);
      int _size = IterableExtensions.size(travNodesWithRightState);
      boolean _greaterThan = (_size > 0);
      if (_greaterThan) {
        System.out.println("Got here inside");
        for (final TraversalNode travNode : travNodesWithRightState) {
          String _plus = (travNode + ", ");
          String _plus_1 = (_plus + condition);
          System.out.println(_plus_1);
        }
      }
    }
    final TraversalCondition travCond = new TraversalCondition(condition);
    boolean isConditionFulfillable = true;
    while ((isConditionFulfillable && travCond.buildNextComparisonChain())) {
      {
        final Function1<Condition, Boolean> _function_1 = (Condition comp) -> {
          boolean _matched = false;
          if (comp instanceof Comparison) {
            _matched=true;
            boolean _checkIfComparisonIsAlreadyAchieved = this.checkIfComparisonIsAlreadyAchieved(((Comparison)comp), traverser);
            boolean _not_1 = (!_checkIfComparisonIsAlreadyAchieved);
            if (_not_1) {
              final Iterable<SystemStateChangeNode> scnodes = this.getVisitedStateChangeNodesThatCanHelpAchieveComparison(((Comparison)comp), traverser);
              int _size_1 = IterableExtensions.size(scnodes);
              boolean _tripleEquals = (_size_1 == 0);
              if (_tripleEquals) {
                return Boolean.valueOf(false);
              }
              for (final SystemStateChangeNode scnode : scnodes) {
                {
                  final Function1<TraversalNode, Boolean> _function_2 = (TraversalNode it) -> {
                    return Boolean.valueOf((ASTTraverser.checkCondition(
                      IterableExtensions.<Transition>findFirst(traverser.getVisitedTransitions(), 
                        ((Function1<Transition, Boolean>) (Transition it_1) -> {
                          Node _destination = it_1.getDestination();
                          return Boolean.valueOf((_destination == scnode));
                        })).getCondition(), 
                      it.getStateSnapshot()) && (it != scnode)));
                  };
                  Node nodeWithRightStateToGetToScnode = IterableExtensions.<TraversalNode>findFirst(traverser.getVisitedNodes().values(), _function_2).getNode();
                  boolean keepSearching = true;
                  while ((keepSearching && traverser.findNodeFrom(nodeWithRightStateToGetToScnode, scnode, 
                    true))) {
                    {
                      boolean _checkIfComparisonIsAlreadyAchieved_1 = this.checkIfComparisonIsAlreadyAchieved(((Comparison)comp), traverser);
                      boolean _not_2 = (!_checkIfComparisonIsAlreadyAchieved_1);
                      keepSearching = _not_2;
                      nodeWithRightStateToGetToScnode = scnode;
                    }
                  }
                  boolean _checkIfComparisonIsAlreadyAchieved_1 = this.checkIfComparisonIsAlreadyAchieved(((Comparison)comp), traverser);
                  return Boolean.valueOf((!_checkIfComparisonIsAlreadyAchieved_1));
                }
              }
            }
          }
          if (!_matched) {
            if (comp instanceof Parentheses) {
              _matched=true;
              return Boolean.valueOf(this.analyseConditionAndTryToFulfillItByTraversingAST(((Parentheses)comp).getInner(), traverser));
            }
          }
          return Boolean.valueOf(false);
        };
        final Condition firstFailedComparison = IterableExtensions.<Condition>findFirst(travCond.getComparisonChain(), _function_1);
        isConditionFulfillable = (firstFailedComparison != null);
      }
    }
    return isConditionFulfillable;
  }

  private boolean checkIfComparisonIsAlreadyAchieved(final Comparison comp, final ASTTraverser traverser) {
    Collection<TraversalNode> _values = traverser.getVisitedNodes().values();
    for (final TraversalNode travNode : _values) {
      boolean _containsKey = travNode.getStateSnapshot().containsKey(comp.getVariable());
      if (_containsKey) {
        String _operator = comp.getOperator();
        if (_operator != null) {
          switch (_operator) {
            case "==":
              Integer _orDefault = travNode.getStateSnapshot().getOrDefault(comp.getVariable(), Integer.valueOf(0));
              int _value = comp.getValue();
              return ((_orDefault).intValue() == _value);
            case "!=":
              Integer _orDefault_1 = travNode.getStateSnapshot().getOrDefault(comp.getVariable(), Integer.valueOf(0));
              int _value_1 = comp.getValue();
              return ((_orDefault_1).intValue() != _value_1);
            case ">":
              Integer _orDefault_2 = travNode.getStateSnapshot().getOrDefault(comp.getVariable(), Integer.valueOf(0));
              int _value_2 = comp.getValue();
              return ((_orDefault_2).intValue() > _value_2);
            case "<":
              Integer _orDefault_3 = travNode.getStateSnapshot().getOrDefault(comp.getVariable(), Integer.valueOf(0));
              int _value_3 = comp.getValue();
              return ((_orDefault_3).intValue() < _value_3);
            case ">=":
              Integer _orDefault_4 = travNode.getStateSnapshot().getOrDefault(comp.getVariable(), Integer.valueOf(0));
              int _value_4 = comp.getValue();
              return ((_orDefault_4).intValue() >= _value_4);
            case "<=":
              Integer _orDefault_5 = travNode.getStateSnapshot().getOrDefault(comp.getVariable(), Integer.valueOf(0));
              int _value_5 = comp.getValue();
              return ((_orDefault_5).intValue() <= _value_5);
          }
        }
      }
    }
    return false;
  }

  private Iterable<SystemStateChangeNode> getVisitedStateChangeNodesThatCanHelpAchieveComparison(final Comparison comp, final ASTTraverser traverser) {
    final Function1<SystemStateChangeNode, Boolean> _function = (SystemStateChangeNode scnode) -> {
      EList<StateUpdate> _stateUpdates = scnode.getStateUpdates();
      for (final StateUpdate stateUpdate : _stateUpdates) {
        boolean _equals = stateUpdate.getVariable().equals(comp.getVariable());
        if (_equals) {
          boolean _equals_1 = "=".equals(stateUpdate.getOperator());
          if (_equals_1) {
            boolean _contains = "<= >= ==".contains(comp.getOperator());
            if (_contains) {
              int _value = stateUpdate.getValue();
              int _value_1 = comp.getValue();
              return Boolean.valueOf((_value == _value_1));
            } else {
              return Boolean.valueOf(false);
            }
          } else {
            boolean _contains_1 = "< <=".contains(comp.getOperator());
            if (_contains_1) {
              return Boolean.valueOf("-=".equals(stateUpdate.getOperator()));
            }
            boolean _contains_2 = "> >=".contains(comp.getOperator());
            if (_contains_2) {
              return Boolean.valueOf("+=".equals(stateUpdate.getOperator()));
            }
            boolean _equals_2 = "==".equals(comp.getOperator());
            if (_equals_2) {
              Collection<TraversalNode> _values = traverser.getVisitedNodes().values();
              for (final TraversalNode travNode : _values) {
                {
                  final Integer current = travNode.getStateSnapshot().getOrDefault(comp.getVariable(), Integer.valueOf(0));
                  int _value_2 = comp.getValue();
                  int _minus = ((current).intValue() - _value_2);
                  int _value_3 = stateUpdate.getValue();
                  int _modulo = (_minus % _value_3);
                  boolean _equals_3 = (_modulo == 0);
                  if (_equals_3) {
                    if ((Objects.equals(stateUpdate.getOperator(), "-=") && (((current).intValue() - stateUpdate.getValue()) >= comp.getValue()))) {
                      return Boolean.valueOf(true);
                    }
                    if ((Objects.equals(stateUpdate.getOperator(), "+=") && (((current).intValue() + stateUpdate.getValue()) <= comp.getValue()))) {
                      return Boolean.valueOf(true);
                    }
                  }
                }
              }
              return Boolean.valueOf(false);
            }
          }
        }
      }
      return Boolean.valueOf(false);
    };
    return IterableExtensions.<SystemStateChangeNode>filter(traverser.getVisitedStateChangeNodes(), _function);
  }

  private HashSet<Node> getNodesNotRefferencedByAnyTransitions(final Story story, final List<Transition> allTransitions) {
    EList<Node> _nodes = story.getNodes();
    HashSet<Node> notRefferencedByTransitions = new HashSet<Node>(_nodes);
    for (final Transition t : allTransitions) {
      boolean _contains = notRefferencedByTransitions.contains(t.getDestination());
      if (_contains) {
        notRefferencedByTransitions.remove(t.getDestination());
      }
    }
    return notRefferencedByTransitions;
  }
}
