/**
 * generated by Xtext 2.42.0
 */
package net.mudcrab.coursework.mbsd.validation;

import com.google.common.collect.Iterables;
import com.google.inject.Inject;
import com.google.inject.Provider;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Predicate;
import net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceNode;
import net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption;
import net.mudcrab.coursework.mbsd.ifictiondsl.Comparison;
import net.mudcrab.coursework.mbsd.ifictiondsl.Condition;
import net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage;
import net.mudcrab.coursework.mbsd.ifictiondsl.Node;
import net.mudcrab.coursework.mbsd.ifictiondsl.Parentheses;
import net.mudcrab.coursework.mbsd.ifictiondsl.StateUpdate;
import net.mudcrab.coursework.mbsd.ifictiondsl.Story;
import net.mudcrab.coursework.mbsd.ifictiondsl.SystemStateChangeNode;
import net.mudcrab.coursework.mbsd.ifictiondsl.Transition;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.util.IResourceScopeCache;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IfictiondslValidator extends AbstractIfictiondslValidator {
  @Inject
  private IResourceScopeCache cache;

  public static final String NOT_REFERENCED_BY_TRANSITION = "notReferencedByTransition";

  public static final String NODE_TRANSITIONS_TO_ITSELF = "nodeTransitionsToItself";

  public static final String NODE_IS_UNREACHABLE = "nodeIsUnreachable";

  public static final String TRANSITION_CONDITION_CANNOT_BE_SATISFIED = "transitionConditionCannotBeSatisfied";

  @Check(CheckType.FAST)
  public void checkNotRefferencedByAnyTransitions(final Node node) {
    int _size = EcoreUtil.UsageCrossReferencer.find(node, node.eContainer()).size();
    boolean _tripleEquals = (_size == 0);
    if (_tripleEquals) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Node is not referenced by any transitions in story");
      this.warning(_builder.toString(), 
        IfictiondslPackage.Literals.NODE__NAME, 
        IfictiondslValidator.NOT_REFERENCED_BY_TRANSITION);
    }
  }

  @Check(CheckType.FAST)
  public void checkNotTransitioningToItself(final Node node) {
    final Provider<HashSet<Node>> _function = () -> {
      return new HashSet<Node>();
    };
    final HashSet<Node> cachedNodesNotVisitedFromConditionlessSearch = this.cache.<HashSet<Node>>get("cachedNodesNotVisitedFromConditionlessSearch", node.eResource(), _function);
    final Provider<HashSet<Node>> _function_1 = () -> {
      return new HashSet<Node>();
    };
    final HashSet<Node> cacheDeadNodes = this.cache.<HashSet<Node>>get("cachedDeadNodes", node.eResource(), _function_1);
    boolean _matched = false;
    if (node instanceof ChoiceNode) {
      _matched=true;
      EList<ChoiceOption> _options = ((ChoiceNode)node).getOptions();
      for (final ChoiceOption option : _options) {
        EList<Transition> _transitions = option.getTransitions();
        for (final Transition transition : _transitions) {
          Node _destination = transition.getDestination();
          boolean _tripleEquals = (_destination == node);
          if (_tripleEquals) {
            if ((cachedNodesNotVisitedFromConditionlessSearch.contains(node) || 
              cacheDeadNodes.contains(node))) {
              StringConcatenation _builder = new StringConcatenation();
              _builder.append("ChoiceOption is transitioning to own ChoiceNode");
              this.warning(_builder.toString(), transition, 
                IfictiondslPackage.Literals.TRANSITION__DESTINATION, 
                IfictiondslValidator.NODE_TRANSITIONS_TO_ITSELF);
            } else {
              StringConcatenation _builder_1 = new StringConcatenation();
              _builder_1.append("ChoiceOption is transitioning to own ChoiceNode");
              this.error(_builder_1.toString(), transition, 
                IfictiondslPackage.Literals.TRANSITION__DESTINATION, 
                IfictiondslValidator.NODE_TRANSITIONS_TO_ITSELF);
            }
          }
        }
      }
    }
    if (!_matched) {
      {
        final EStructuralFeature structuralFeature = node.eClass().getEStructuralFeature("transition");
        if ((structuralFeature != null)) {
          Object _eGet = node.eGet(structuralFeature);
          final Transition transition = ((Transition) _eGet);
          Node _destination = transition.getDestination();
          boolean _tripleEquals = (_destination == node);
          if (_tripleEquals) {
            if ((cachedNodesNotVisitedFromConditionlessSearch.contains(node) || 
              cacheDeadNodes.contains(node))) {
              StringConcatenation _builder = new StringConcatenation();
              _builder.append("Node is transitioning to itself");
              this.warning(_builder.toString(), transition, 
                IfictiondslPackage.Literals.TRANSITION__DESTINATION, 
                IfictiondslValidator.NODE_TRANSITIONS_TO_ITSELF);
            } else {
              StringConcatenation _builder_1 = new StringConcatenation();
              _builder_1.append("Node is transitioning to itself");
              this.error(_builder_1.toString(), transition, 
                IfictiondslPackage.Literals.TRANSITION__DESTINATION, 
                IfictiondslValidator.NODE_TRANSITIONS_TO_ITSELF);
            }
          }
        }
      }
    }
  }

  @Check(CheckType.FAST)
  public boolean checkDetectDeadNodes(final Story story) {
    boolean _xblockexpression = false;
    {
      final ASTTraverser traverser = new ASTTraverser();
      traverser.traverseStory(story);
      final List<Transition> allTransitions = EcoreUtil2.<Transition>getAllContentsOfType(story, Transition.class);
      HashSet<Node> deadNodeCandidates = new HashSet<Node>();
      EList<Node> _nodes = story.getNodes();
      for (final Node node : _nodes) {
        boolean _containsKey = traverser.getVisitedNodes().containsKey(node);
        boolean _not = (!_containsKey);
        if (_not) {
          deadNodeCandidates.add(node);
        }
      }
      HashSet<Node> _nodesNotRefferencedByAnyTransitions = this.getNodesNotRefferencedByAnyTransitions(story, allTransitions);
      for (final Node notRefedNode : _nodesNotRefferencedByAnyTransitions) {
        deadNodeCandidates.remove(notRefedNode);
      }
      traverser.traverseStoryConditionlessly(story);
      final Function1<Node, Boolean> _function = (Node it) -> {
        boolean _contains = traverser.getConditionlessSearchVisitedNotes().contains(it);
        return Boolean.valueOf((!_contains));
      };
      final Iterable<Node> notVisitedNodesFromConditionlessSearch = IterableExtensions.<Node>filter(story.getNodes(), _function);
      for (final Node nodeNVFCS : notVisitedNodesFromConditionlessSearch) {
        {
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("Node is unreachable. As no node visitable from starting at the StartNode transitions to it.");
          this.warning(_builder.toString(), nodeNVFCS, 
            IfictiondslPackage.Literals.NODE__NAME, 
            IfictiondslValidator.NODE_IS_UNREACHABLE);
          deadNodeCandidates.remove(nodeNVFCS);
        }
      }
      final HashSet<Transition> transitionCandidates = new HashSet<Transition>();
      final HashSet<Node> furtherDownTheDeadBranchNodes = new HashSet<Node>();
      this.splitDeadNodeCandidatesAndFurtherDownDeadBranchCandidates(deadNodeCandidates, transitionCandidates, furtherDownTheDeadBranchNodes, allTransitions, traverser);
      int deadNodeCandidateCount = 0;
      do {
        {
          final HashSet<Node> _converted_deadNodeCandidates = (HashSet<Node>)deadNodeCandidates;
          deadNodeCandidateCount = ((Object[])Conversions.unwrapArray(_converted_deadNodeCandidates, Object.class)).length;
          for (final Transition transCand : transitionCandidates) {
            {
              ConcurrentHashMap<Node, TraversalNode> _visitedNodes = traverser.getVisitedNodes();
              final Function1<TraversalNode, Boolean> _function_1 = (TraversalNode it) -> {
                return Boolean.valueOf(ASTTraverser.checkCondition(transCand.getCondition(), it.getStateSnapshot()));
              };
              final Iterable<TraversalNode> travNodesWithRightState = IterableExtensions.<TraversalNode>filter(new HashMap<Node, TraversalNode>(_visitedNodes).values(), _function_1);
              for (final TraversalNode travNode : travNodesWithRightState) {
                if (((travNode != null) && 
                  traverser.findNodeFrom(travNode.getNode(), transCand.getDestination()))) {
                }
              }
            }
          }
          Object[] _array = deadNodeCandidates.toArray();
          for (final Object deadNodeCand : _array) {
            boolean _containsKey_1 = traverser.getVisitedNodes().containsKey(deadNodeCand);
            if (_containsKey_1) {
              deadNodeCandidates.remove(deadNodeCand);
              final Predicate<Transition> _function_1 = (Transition it) -> {
                return it.getDestination().equals(deadNodeCand);
              };
              transitionCandidates.removeIf(_function_1);
            }
          }
        }
      } while((deadNodeCandidateCount > ((Object[])Conversions.unwrapArray(deadNodeCandidates, Object.class)).length));
      boolean keepGoing = true;
      while (keepGoing) {
        {
          final Function1<Transition, Integer> _function_1 = (Transition it) -> {
            int _priority = it.getPriority();
            return Integer.valueOf((-_priority));
          };
          final List<Transition> transCandidatedsSortedByPriority = IterableExtensions.<Transition, Integer>sortBy(transitionCandidates, _function_1);
          boolean _analyseConditionAndTryToFulfillItByTraversingASTForEach = this.analyseConditionAndTryToFulfillItByTraversingASTForEach(transCandidatedsSortedByPriority, traverser);
          if (_analyseConditionAndTryToFulfillItByTraversingASTForEach) {
            final Predicate<Node> _function_2 = (Node deadNodeCand) -> {
              boolean _containsKey_1 = traverser.getVisitedNodes().containsKey(deadNodeCand);
              if (_containsKey_1) {
                final Predicate<Transition> _function_3 = (Transition it) -> {
                  return it.getDestination().equals(deadNodeCand);
                };
                transitionCandidates.removeIf(_function_3);
                return true;
              } else {
                return false;
              }
            };
            deadNodeCandidates.removeIf(_function_2);
            deadNodeCandidates.addAll(furtherDownTheDeadBranchNodes);
            final Function1<Transition, Boolean> _function_3 = (Transition transCand) -> {
              return Boolean.valueOf(furtherDownTheDeadBranchNodes.contains(transCand.getDestination()));
            };
            Iterables.<Transition>addAll(transitionCandidates, IterableExtensions.<Transition>filter(allTransitions, _function_3));
            furtherDownTheDeadBranchNodes.clear();
            this.splitDeadNodeCandidatesAndFurtherDownDeadBranchCandidates(furtherDownTheDeadBranchNodes, transitionCandidates, furtherDownTheDeadBranchNodes, allTransitions, traverser);
          } else {
            keepGoing = false;
          }
        }
      }
      for (final Node deadNode : deadNodeCandidates) {
        {
          final HashSet<Transition> tCToDN = new HashSet<Transition>();
          for (final Transition transCand : transitionCandidates) {
            Node _destination = transCand.getDestination();
            boolean _tripleEquals = (_destination == deadNode);
            if (_tripleEquals) {
              tCToDN.add(transCand);
              StringConcatenation _builder = new StringConcatenation();
              _builder.append("Transition condition cannot be satisfied from traversing the story and destination node: \"");
              String _name = transCand.getDestination().getName();
              _builder.append(_name);
              _builder.append("\" is therefore unreachable");
              this.warning(_builder.toString(), transCand, 
                IfictiondslPackage.Literals.TRANSITION__CONDITION, 
                IfictiondslValidator.TRANSITION_CONDITION_CANNOT_BE_SATISFIED);
            }
          }
          StringConcatenation _builder_1 = new StringConcatenation();
          _builder_1.append("Node is unreachable. Transition condition");
          String _xifexpression = null;
          int _size = tCToDN.size();
          boolean _greaterThan = (_size > 1);
          if (_greaterThan) {
            _xifexpression = "s";
          } else {
            _xifexpression = "";
          }
          _builder_1.append(_xifexpression);
          _builder_1.append(" from node");
          String _xifexpression_1 = null;
          int _size_1 = tCToDN.size();
          boolean _greaterThan_1 = (_size_1 > 1);
          if (_greaterThan_1) {
            _xifexpression_1 = "s";
          } else {
            _xifexpression_1 = "";
          }
          _builder_1.append(_xifexpression_1);
          _builder_1.append(": ");
          {
            boolean _hasElements = false;
            for(final Transition t : tCToDN) {
              if (!_hasElements) {
                _hasElements = true;
              } else {
                _builder_1.appendImmediate(", ", "");
              }
              _builder_1.newLineIfNotEmpty();
              CharSequence _switchResult = null;
              EObject _eContainer = t.eContainer();
              boolean _matched = false;
              if (_eContainer instanceof ChoiceOption) {
                _matched=true;
                StringConcatenation _builder_2 = new StringConcatenation();
                _builder_2.append("\"");
                EObject _eContainer_1 = t.eContainer().eContainer();
                String _name_1 = ((ChoiceNode) _eContainer_1).getName();
                _builder_2.append(_name_1);
                _builder_2.append("\"");
                _switchResult = _builder_2;
              }
              if (!_matched) {
                StringConcatenation _builder_2 = new StringConcatenation();
                _builder_2.append("\"");
                EObject _eContainer_1 = t.eContainer();
                String _name_1 = ((Node) _eContainer_1).getName();
                _builder_2.append(_name_1);
                _builder_2.append("\"");
                _switchResult = _builder_2;
              }
              _builder_1.append(_switchResult);
            }
          }
          _builder_1.append(" cannot be satisfied");
          this.warning(_builder_1.toString(), deadNode, 
            IfictiondslPackage.Literals.NODE__NAME, 
            IfictiondslValidator.NODE_IS_UNREACHABLE);
          this.putWarningsOnDeadNodesDownDeadBranch(deadNode, traverser);
        }
      }
      final Provider<HashSet<Node>> _function_1 = () -> {
        return new HashSet<Node>();
      };
      final HashSet<Node> cachedDeadNodes = this.cache.<HashSet<Node>>get("cachedDeadNodes", story.eResource(), _function_1);
      cachedDeadNodes.addAll(deadNodeCandidates);
      final Provider<HashSet<Node>> _function_2 = () -> {
        return new HashSet<Node>();
      };
      final HashSet<Node> cachedNodesNotVisitedFromConditionlessSearch = this.cache.<HashSet<Node>>get("cachedNodesNotVisitedFromConditionlessSearch", story.eResource(), _function_2);
      _xblockexpression = Iterables.<Node>addAll(cachedNodesNotVisitedFromConditionlessSearch, notVisitedNodesFromConditionlessSearch);
    }
    return _xblockexpression;
  }

  private void splitDeadNodeCandidatesAndFurtherDownDeadBranchCandidates(final HashSet<Node> deadNodeCandidates, final HashSet<Transition> transitionCandidates, final HashSet<Node> furtherDownTheDeadBranchNodes, final List<Transition> allTransitions, final ASTTraverser traverser) {
    Object[] _array = deadNodeCandidates.toArray();
    for (final Object deadNodeCand : _array) {
      {
        boolean keep = false;
        for (final Transition transition : allTransitions) {
          Node _destination = transition.getDestination();
          boolean _tripleEquals = (_destination == deadNodeCand);
          if (_tripleEquals) {
            EObject container = transition.eContainer();
            if ((container instanceof ChoiceOption)) {
              container = ((ChoiceOption)container).eContainer();
            }
            boolean _containsKey = traverser.getVisitedNodes().containsKey(container);
            if (_containsKey) {
              transitionCandidates.add(transition);
              keep = true;
            }
          }
        }
        if ((!keep)) {
          keep = false;
          deadNodeCandidates.remove(deadNodeCand);
          furtherDownTheDeadBranchNodes.add(((Node) deadNodeCand));
        }
      }
    }
  }

  private void putWarningsOnDeadNodesDownDeadBranch(final Node deadNode, final ASTTraverser traverser) {
    boolean _matched = false;
    if (deadNode instanceof ChoiceNode) {
      _matched=true;
      EList<ChoiceOption> _options = ((ChoiceNode)deadNode).getOptions();
      for (final ChoiceOption option : _options) {
        EList<Transition> _transitions = option.getTransitions();
        for (final Transition transition : _transitions) {
          boolean _containsKey = traverser.getVisitedNodes().containsKey(transition.getDestination());
          boolean _not = (!_containsKey);
          if (_not) {
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("Node is unreachable because parent node: \"");
            String _name = ((ChoiceNode)deadNode).getName();
            _builder.append(_name);
            _builder.append("\" is unreachable.");
            this.warning(_builder.toString(), 
              transition.getDestination(), 
              IfictiondslPackage.Literals.NODE__NAME, 
              IfictiondslValidator.NODE_IS_UNREACHABLE);
            this.putWarningsOnDeadNodesDownDeadBranch(transition.getDestination(), traverser);
          }
        }
      }
    }
    if (!_matched) {
      {
        final EStructuralFeature structuralFeature = deadNode.eClass().getEStructuralFeature("transition");
        if ((structuralFeature != null)) {
          Object _eGet = deadNode.eGet(structuralFeature);
          final Transition transition = ((Transition) _eGet);
          if (((transition != null) && (!traverser.getVisitedNodes().containsKey(transition.getDestination())))) {
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("Node is unreachable because parent node: \"");
            String _name = deadNode.getName();
            _builder.append(_name);
            _builder.append("\" is unreachable.");
            this.warning(_builder.toString(), 
              transition.getDestination(), 
              IfictiondslPackage.Literals.NODE__NAME, 
              IfictiondslValidator.NODE_IS_UNREACHABLE);
            this.putWarningsOnDeadNodesDownDeadBranch(transition.getDestination(), traverser);
          }
        }
      }
    }
  }

  private boolean analyseConditionAndTryToFulfillItByTraversingASTForEach(final List<Transition> transCandidatedsSortedByPriority, final ASTTraverser traverser) {
    boolean succeeded = false;
    for (final Transition transCand : transCandidatedsSortedByPriority) {
      boolean _analyseConditionAndTryToFulfillItByTraversingAST = this.analyseConditionAndTryToFulfillItByTraversingAST(transCand.getCondition(), traverser);
      if (_analyseConditionAndTryToFulfillItByTraversingAST) {
        final Function1<TraversalNode, Boolean> _function = (TraversalNode node) -> {
          return Boolean.valueOf(ASTTraverser.checkCondition(
            transCand.getCondition(), 
            node.getStateSnapshot()));
        };
        Iterable<TraversalNode> nodesWithRightStateToGetToDeadNodeCandidate = IterableExtensions.<TraversalNode>filter(traverser.getVisitedNodes().values(), _function);
        boolean _isEmpty = IterableExtensions.isEmpty(nodesWithRightStateToGetToDeadNodeCandidate);
        boolean _not = (!_isEmpty);
        if (_not) {
          final Function1<TraversalNode, Boolean> _function_1 = (TraversalNode travNode) -> {
            return Boolean.valueOf(traverser.findNodeFrom(travNode.getNode(), transCand.getDestination(), true));
          };
          TraversalNode _findFirst = IterableExtensions.<TraversalNode>findFirst(nodesWithRightStateToGetToDeadNodeCandidate, _function_1);
          boolean _tripleNotEquals = (_findFirst != null);
          if (_tripleNotEquals) {
            succeeded = true;
          }
        } else {
        }
      } else {
      }
    }
    return succeeded;
  }

  private boolean analyseConditionAndTryToFulfillItByTraversingAST(final Condition condition, final ASTTraverser traverser) {
    final TraversalCondition travCond = new TraversalCondition(condition);
    boolean isConditionFulfillable = true;
    while ((isConditionFulfillable && travCond.buildNextComparisonChain())) {
      {
        final Function1<Condition, Boolean> _function = (Condition comp) -> {
          boolean _matched = false;
          if (comp instanceof Comparison) {
            _matched=true;
            boolean _checkIfComparisonIsAchievedByAnyVisitedNode = this.checkIfComparisonIsAchievedByAnyVisitedNode(((Comparison)comp), traverser);
            boolean _not = (!_checkIfComparisonIsAchievedByAnyVisitedNode);
            if (_not) {
              final Iterable<SystemStateChangeNode> scnodes = this.getVisitedStateChangeNodesThatCanHelpAchieveComparison(((Comparison)comp), traverser);
              int _size = IterableExtensions.size(scnodes);
              boolean _tripleEquals = (_size == 0);
              if (_tripleEquals) {
                return Boolean.valueOf(true);
              }
              List<SystemStateChangeNode> _list = IterableExtensions.<SystemStateChangeNode>toList(scnodes);
              for (final SystemStateChangeNode scnode : _list) {
                {
                  final Function1<Transition, Boolean> _function_1 = (Transition trans) -> {
                    Node _destination = trans.getDestination();
                    return Boolean.valueOf((_destination == scnode));
                  };
                  final Transition transitionToScnode = IterableExtensions.<Transition>findFirst(traverser.getVisitedTransitions(), _function_1);
                  final Function1<TraversalNode, Boolean> _function_2 = (TraversalNode node) -> {
                    return Boolean.valueOf(ASTTraverser.checkCondition(
                      transitionToScnode.getCondition(), 
                      node.getStateSnapshot()));
                  };
                  Node nodeWithRightStateToGetToScnode = IterableExtensions.<TraversalNode>findFirst(traverser.getVisitedNodes().values(), _function_2).getNode();
                  while (((!this.checkIfComparisonIsAchievedByAnyVisitedNode(((Comparison)comp), traverser)) && traverser.findNodeFrom(nodeWithRightStateToGetToScnode, scnode, 
                    true))) {
                    nodeWithRightStateToGetToScnode = scnode;
                  }
                  boolean _checkIfComparisonIsAchievedByAnyVisitedNode_1 = this.checkIfComparisonIsAchievedByAnyVisitedNode(((Comparison)comp), traverser);
                  if (_checkIfComparisonIsAchievedByAnyVisitedNode_1) {
                    return Boolean.valueOf(false);
                  }
                }
              }
              return Boolean.valueOf(true);
            } else {
              return Boolean.valueOf(false);
            }
          }
          if (!_matched) {
            if (comp instanceof Parentheses) {
              _matched=true;
              return Boolean.valueOf(this.analyseConditionAndTryToFulfillItByTraversingAST(((Parentheses)comp).getInner(), traverser));
            }
          }
          System.out.println("We should not be able to get here");
          return Boolean.valueOf(false);
        };
        final Condition firstFailedComparison = IterableExtensions.<Condition>findFirst(travCond.getComparisonChain(), _function);
        isConditionFulfillable = (firstFailedComparison == null);
      }
    }
    return isConditionFulfillable;
  }

  private boolean checkIfComparisonIsAchievedByAnyVisitedNode(final Comparison comp, final ASTTraverser traverser) {
    Collection<TraversalNode> _values = traverser.getVisitedNodes().values();
    for (final TraversalNode travNode : _values) {
      boolean _containsKey = travNode.getStateSnapshot().containsKey(comp.getVariable());
      if (_containsKey) {
        boolean _checkCondition = ASTTraverser.checkCondition(comp, travNode.getStateSnapshot());
        if (_checkCondition) {
          return true;
        }
      }
    }
    return false;
  }

  private Iterable<SystemStateChangeNode> getVisitedStateChangeNodesThatCanHelpAchieveComparison(final Comparison comp, final ASTTraverser traverser) {
    final Function1<SystemStateChangeNode, Boolean> _function = (SystemStateChangeNode scnode) -> {
      EList<StateUpdate> _stateUpdates = scnode.getStateUpdates();
      for (final StateUpdate stateUpdate : _stateUpdates) {
        boolean _equals = stateUpdate.getVariable().equals(comp.getVariable());
        if (_equals) {
          boolean _equals_1 = "=".equals(stateUpdate.getOperator());
          if (_equals_1) {
            boolean _contains = "<= >= ==".contains(comp.getOperator());
            if (_contains) {
              int _value = stateUpdate.getValue();
              int _value_1 = comp.getValue();
              return Boolean.valueOf((_value == _value_1));
            } else {
              return Boolean.valueOf(false);
            }
          } else {
            boolean _contains_1 = "< <=".contains(comp.getOperator());
            if (_contains_1) {
              return Boolean.valueOf("-=".equals(stateUpdate.getOperator()));
            }
            boolean _contains_2 = "> >=".contains(comp.getOperator());
            if (_contains_2) {
              return Boolean.valueOf("+=".equals(stateUpdate.getOperator()));
            }
            boolean _equals_2 = "==".equals(comp.getOperator());
            if (_equals_2) {
              Collection<TraversalNode> _values = traverser.getVisitedNodes().values();
              for (final TraversalNode travNode : _values) {
                {
                  final Integer current = travNode.getStateSnapshot().getOrDefault(comp.getVariable(), Integer.valueOf(0));
                  int _value_2 = comp.getValue();
                  int _minus = ((current).intValue() - _value_2);
                  int _value_3 = stateUpdate.getValue();
                  int _modulo = (_minus % _value_3);
                  boolean _equals_3 = (_modulo == 0);
                  if (_equals_3) {
                    if ((Objects.equals(stateUpdate.getOperator(), "-=") && (((current).intValue() - stateUpdate.getValue()) >= comp.getValue()))) {
                      return Boolean.valueOf(true);
                    }
                    if ((Objects.equals(stateUpdate.getOperator(), "+=") && (((current).intValue() + stateUpdate.getValue()) <= comp.getValue()))) {
                      return Boolean.valueOf(true);
                    }
                  }
                }
              }
              return Boolean.valueOf(false);
            }
          }
        }
      }
      return Boolean.valueOf(false);
    };
    return IterableExtensions.<SystemStateChangeNode>filter(traverser.getVisitedStateChangeNodes(), _function);
  }

  private HashSet<Node> getNodesNotRefferencedByAnyTransitions(final Story story, final List<Transition> allTransitions) {
    EList<Node> _nodes = story.getNodes();
    HashSet<Node> notRefferencedByTransitions = new HashSet<Node>(_nodes);
    for (final Transition t : allTransitions) {
      boolean _contains = notRefferencedByTransitions.contains(t.getDestination());
      if (_contains) {
        notRefferencedByTransitions.remove(t.getDestination());
      }
    }
    return notRefferencedByTransitions;
  }
}
