/*
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIfictiondslScopeProvider extends DelegatingScopeProvider {
}
