/**
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.generator;

import com.google.common.collect.Iterables;
import java.net.URI;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.function.Consumer;
import java.util.stream.Stream;
import net.mudcrab.coursework.mbsd.ifictiondsl.And;
import net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceNode;
import net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption;
import net.mudcrab.coursework.mbsd.ifictiondsl.Comparison;
import net.mudcrab.coursework.mbsd.ifictiondsl.Condition;
import net.mudcrab.coursework.mbsd.ifictiondsl.DialogueNode;
import net.mudcrab.coursework.mbsd.ifictiondsl.EndNode;
import net.mudcrab.coursework.mbsd.ifictiondsl.Node;
import net.mudcrab.coursework.mbsd.ifictiondsl.Or;
import net.mudcrab.coursework.mbsd.ifictiondsl.Parentheses;
import net.mudcrab.coursework.mbsd.ifictiondsl.StartNode;
import net.mudcrab.coursework.mbsd.ifictiondsl.StateUpdate;
import net.mudcrab.coursework.mbsd.ifictiondsl.Story;
import net.mudcrab.coursework.mbsd.ifictiondsl.SystemStateChangeNode;
import net.mudcrab.coursework.mbsd.ifictiondsl.Transition;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import org.eclipse.xtext.xbase.lib.StringExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class IfictiondslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final List<Story> stories = IterableExtensions.<Story>toList(Iterables.<Story>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), Story.class));
    for (final Story story : stories) {
      {
        String _sanitizeClassName = this.sanitizeClassName(story.getName());
        String _plus = ("Example" + _sanitizeClassName);
        String _plus_1 = (_plus + "/");
        String _sanitizeClassName_1 = this.sanitizeClassName(story.getName());
        String _plus_2 = (_plus_1 + _sanitizeClassName_1);
        String _plus_3 = (_plus_2 + "Builder.java");
        fsa.generateFile(_plus_3, 
          this.generateStory(story));
        String _sanitizeClassName_2 = this.sanitizeClassName(story.getName());
        String _plus_4 = ("Example" + _sanitizeClassName_2);
        String _plus_5 = (_plus_4 + "/Main.java");
        fsa.generateFile(_plus_5, 
          this.generateMain(story));
      }
    }
    this.copyTemplateFolder(fsa, "/src/net/mudcrab/coursework/mbsd/generator/LanguageModel", "LanguageModel");
    this.copyTemplateFolder(fsa, "/src/net/mudcrab/coursework/mbsd/generator/Utils", "Utils");
  }

  private void copyTemplateFolder(final IFileSystemAccess2 fsa, final String sourceFolder, final String targetFolder) {
    try {
      try {
        final URL codeSourceUrl = this.getClass().getProtectionDomain().getCodeSource().getLocation();
        String _string = codeSourceUrl.toString();
        String _plus = (_string + sourceFolder);
        final Path start = Paths.get(URI.create(_plus));
        final Stream<Path> stream = Files.walk(start);
        try {
          final Consumer<Path> _function = (Path file) -> {
            try {
              boolean _endsWith = file.toString().endsWith(".javaTmpl");
              if (_endsWith) {
                String _replace = file.getFileName().toString().replace(".javaTmpl", ".java");
                String _plus_1 = ((targetFolder + "/") + _replace);
                fsa.generateFile(_plus_1, 
                  Files.readString(file, StandardCharsets.UTF_8));
              }
            } catch (Throwable _e) {
              throw Exceptions.sneakyThrow(_e);
            }
          };
          stream.forEach(_function);
        } finally {
          stream.close();
        }
      } catch (final Throwable _t) {
        if (_t instanceof Exception) {
          final Exception e = (Exception)_t;
          String _message = e.getMessage();
          String _plus_1 = ((("Failed to copy template folder " + sourceFolder) + ": ") + _message);
          System.err.println(_plus_1);
          throw e;
        } else {
          throw Exceptions.sneakyThrow(_t);
        }
      }
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  private CharSequence generateMain(final Story story) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package Example");
    String _sanitizeClassName = this.sanitizeClassName(story.getName());
    _builder.append(_sanitizeClassName);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("import LanguageModel.StoryEngine;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("public class Main {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public static void main(String args[]) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("new StoryEngine(new ");
    String _sanitizeClassName_1 = this.sanitizeClassName(story.getName());
    _builder.append(_sanitizeClassName_1, "            ");
    _builder.append("Builder()).run();");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("catch (IllegalStateException e) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("System.err.println(e.getMessage());");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  private CharSequence generateStory(final Story story) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package Example");
    String _sanitizeClassName = this.sanitizeClassName(story.getName());
    _builder.append(_sanitizeClassName);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("import LanguageModel.StoryBuilder;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ");
    String _sanitizeClassName_1 = this.sanitizeClassName(story.getName());
    _builder.append(_sanitizeClassName_1);
    _builder.append("Builder extends StoryBuilder {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void build() throws IllegalStateException {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Story(\"");
    String _name = story.getName();
    _builder.append(_name, "\t\t");
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    {
      EList<Node> _nodes = story.getNodes();
      for(final Node node : _nodes) {
        _builder.append("\t\t\t");
        String _generateNode = this.generateNode(node);
        _builder.append(_generateNode, "\t\t\t");
      }
    }
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  private String generateNode(final Node node) {
    String _switchResult = null;
    boolean _matched = false;
    if (node instanceof StartNode) {
      _matched=true;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append(".Start(\"");
      String _name = ((StartNode)node).getName();
      _builder.append(_name);
      _builder.append("\",");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t");
      _builder.append("\"");
      String _sanitizeText = this.sanitizeText(((StartNode)node).getText());
      _builder.append(_sanitizeText, "\t\t");
      _builder.append("\")");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.append(".Transition(");
      String _generateTransition = this.generateTransition(((StartNode)node).getTransition());
      _builder.append(_generateTransition, "\t");
      _builder.append(")");
      _builder.newLineIfNotEmpty();
      _switchResult = _builder.toString();
    }
    if (!_matched) {
      if (node instanceof DialogueNode) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.newLine();
        _builder.append(".Dialogue(\"");
        String _name = ((DialogueNode)node).getName();
        _builder.append(_name);
        _builder.append("\",");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("\"");
        String _sanitizeText = this.sanitizeText(((DialogueNode)node).getText());
        _builder.append(_sanitizeText, "\t\t");
        _builder.append("\")");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append(".Transition(");
        String _generateTransition = this.generateTransition(((DialogueNode)node).getTransition());
        _builder.append(_generateTransition, "\t");
        _builder.append(")");
        _builder.newLineIfNotEmpty();
        _switchResult = _builder.toString();
      }
    }
    if (!_matched) {
      if (node instanceof ChoiceNode) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.newLine();
        _builder.append(".Choice(\"");
        String _name = ((ChoiceNode)node).getName();
        _builder.append(_name);
        _builder.append("\")");
        _builder.newLineIfNotEmpty();
        {
          EList<ChoiceOption> _options = ((ChoiceNode)node).getOptions();
          for(final ChoiceOption option : _options) {
            _builder.append("\t");
            _builder.append(".ChoiceOption(\"");
            String _sanitizeText = this.sanitizeText(option.getText());
            _builder.append(_sanitizeText, "\t");
            _builder.append("\")");
            _builder.newLineIfNotEmpty();
            {
              EList<Transition> _transitions = option.getTransitions();
              for(final Transition trans : _transitions) {
                _builder.append("\t");
                _builder.append("\t");
                _builder.append(".Transition(");
                String _generateTransition = this.generateTransition(trans);
                _builder.append(_generateTransition, "\t\t");
                _builder.append(")");
                _builder.newLineIfNotEmpty();
              }
            }
          }
        }
        _switchResult = _builder.toString();
      }
    }
    if (!_matched) {
      if (node instanceof SystemStateChangeNode) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.newLine();
        _builder.append(".SystemStateChange(\"");
        String _name = ((SystemStateChangeNode)node).getName();
        _builder.append(_name);
        _builder.append("\",");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("\"");
        String _sanitizeText = this.sanitizeText(((SystemStateChangeNode)node).getText());
        _builder.append(_sanitizeText, "\t\t");
        _builder.append("\",");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("\"");
        final Function1<StateUpdate, String> _function = (StateUpdate it) -> {
          return this.generateStateUpdate(it);
        };
        String _join = IterableExtensions.join(ListExtensions.<StateUpdate, String>map(((SystemStateChangeNode)node).getStateUpdates(), _function), ", ");
        _builder.append(_join, "\t\t");
        _builder.append("\")");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append(".Transition(");
        String _generateTransition = this.generateTransition(((SystemStateChangeNode)node).getTransition());
        _builder.append(_generateTransition, "\t");
        _builder.append(")");
        _builder.newLineIfNotEmpty();
        _switchResult = _builder.toString();
      }
    }
    if (!_matched) {
      if (node instanceof EndNode) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.newLine();
        _builder.newLine();
        _builder.append(".End(\"");
        String _name = ((EndNode)node).getName();
        _builder.append(_name);
        _builder.append("\",");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("\"");
        String _sanitizeText = this.sanitizeText(((EndNode)node).getText());
        _builder.append(_sanitizeText, "\t\t");
        _builder.append("\")");
        _switchResult = _builder.toString();
      }
    }
    if (!_matched) {
      StringConcatenation _builder = new StringConcatenation();
      _switchResult = _builder.toString();
    }
    return _switchResult;
  }

  private String generateStateUpdate(final StateUpdate stateUpd) {
    StringConcatenation _builder = new StringConcatenation();
    String _variable = stateUpd.getVariable();
    _builder.append(_variable);
    String _operator = stateUpd.getOperator();
    _builder.append(_operator);
    int _value = stateUpd.getValue();
    _builder.append(_value);
    return _builder.toString();
  }

  private String generateTransition(final Transition transition) {
    final int prio = transition.getPriority();
    if ((prio <= 0)) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("\"");
      String _name = transition.getDestination().getName();
      _builder.append(_name);
      _builder.append("\"");
      return _builder.toString();
    } else {
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("\"");
      String _name_1 = transition.getDestination().getName();
      _builder_1.append(_name_1);
      _builder_1.append("\", ");
      _builder_1.append(prio);
      _builder_1.append(", \"");
      String _trim = this.generateCondition(transition.getCondition()).trim();
      _builder_1.append(_trim);
      _builder_1.append("\"");
      return _builder_1.toString();
    }
  }

  private String generateCondition(final Condition cond) {
    String _switchResult = null;
    boolean _matched = false;
    if (cond instanceof Parentheses) {
      _matched=true;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("(");
      String _generateCondition = this.generateCondition(((Parentheses)cond).getInner());
      _builder.append(_generateCondition);
      _builder.append(")");
      _switchResult = _builder.toString();
    }
    if (!_matched) {
      if (cond instanceof And) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        String _generateCondition = this.generateCondition(((And)cond).getLeft());
        _builder.append(_generateCondition);
        _builder.append(" and ");
        String _generateCondition_1 = this.generateCondition(((And)cond).getRight());
        _builder.append(_generateCondition_1);
        _switchResult = _builder.toString();
      }
    }
    if (!_matched) {
      if (cond instanceof Or) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        String _generateCondition = this.generateCondition(((Or)cond).getLeft());
        _builder.append(_generateCondition);
        _builder.append(" or ");
        String _generateCondition_1 = this.generateCondition(((Or)cond).getRight());
        _builder.append(_generateCondition_1);
        _switchResult = _builder.toString();
      }
    }
    if (!_matched) {
      if (cond instanceof Comparison) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        String _variable = ((Comparison)cond).getVariable();
        _builder.append(_variable);
        String _operator = ((Comparison)cond).getOperator();
        _builder.append(_operator);
        int _value = ((Comparison)cond).getValue();
        _builder.append(_value);
        _switchResult = _builder.toString();
      }
    }
    if (!_matched) {
      StringConcatenation _builder = new StringConcatenation();
      _switchResult = _builder.toString();
    }
    return _switchResult;
  }

  private String sanitizeClassName(final String s) {
    final Function1<String, String> _function = (String it) -> {
      return StringExtensions.toFirstUpper(it);
    };
    return IterableExtensions.join(ListExtensions.<String, String>map(((List<String>)Conversions.doWrapArray(s.split(" "))), _function), "").replace("-", "_");
  }

  private String sanitizeText(final String s) {
    return s.replace("\n", "\\n").replace("\r", "\\r").replace("\"", "\\\"");
  }
}
