/**
 * generated by Xtext 2.41.0
 */
package net.mudcrab.coursework.mbsd.ifictiondsl.util;

import net.mudcrab.coursework.mbsd.ifictiondsl.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see net.mudcrab.coursework.mbsd.ifictiondsl.IfictiondslPackage
 * @generated
 */
public class IfictiondslAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static IfictiondslPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IfictiondslAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = IfictiondslPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IfictiondslSwitch<Adapter> modelSwitch =
    new IfictiondslSwitch<Adapter>()
    {
      @Override
      public Adapter caseStory(Story object)
      {
        return createStoryAdapter();
      }
      @Override
      public Adapter caseNode(Node object)
      {
        return createNodeAdapter();
      }
      @Override
      public Adapter caseChoiceNode(ChoiceNode object)
      {
        return createChoiceNodeAdapter();
      }
      @Override
      public Adapter caseChoiceOption(ChoiceOption object)
      {
        return createChoiceOptionAdapter();
      }
      @Override
      public Adapter caseTransition(Transition object)
      {
        return createTransitionAdapter();
      }
      @Override
      public Adapter caseStartNode(StartNode object)
      {
        return createStartNodeAdapter();
      }
      @Override
      public Adapter caseDialogueNode(DialogueNode object)
      {
        return createDialogueNodeAdapter();
      }
      @Override
      public Adapter caseCondition(Condition object)
      {
        return createConditionAdapter();
      }
      @Override
      public Adapter caseComparison(Comparison object)
      {
        return createComparisonAdapter();
      }
      @Override
      public Adapter caseSystemStateChangeNode(SystemStateChangeNode object)
      {
        return createSystemStateChangeNodeAdapter();
      }
      @Override
      public Adapter caseStateUpdate(StateUpdate object)
      {
        return createStateUpdateAdapter();
      }
      @Override
      public Adapter caseEndNode(EndNode object)
      {
        return createEndNodeAdapter();
      }
      @Override
      public Adapter caseOr(Or object)
      {
        return createOrAdapter();
      }
      @Override
      public Adapter caseAnd(And object)
      {
        return createAndAdapter();
      }
      @Override
      public Adapter caseParentheses(Parentheses object)
      {
        return createParenthesesAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.Story <em>Story</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.Story
   * @generated
   */
  public Adapter createStoryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.Node
   * @generated
   */
  public Adapter createNodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceNode <em>Choice Node</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceNode
   * @generated
   */
  public Adapter createChoiceNodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption <em>Choice Option</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.ChoiceOption
   * @generated
   */
  public Adapter createChoiceOptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.Transition
   * @generated
   */
  public Adapter createTransitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.StartNode <em>Start Node</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.StartNode
   * @generated
   */
  public Adapter createStartNodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.DialogueNode <em>Dialogue Node</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.DialogueNode
   * @generated
   */
  public Adapter createDialogueNodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.Condition
   * @generated
   */
  public Adapter createConditionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.Comparison <em>Comparison</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.Comparison
   * @generated
   */
  public Adapter createComparisonAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.SystemStateChangeNode <em>System State Change Node</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.SystemStateChangeNode
   * @generated
   */
  public Adapter createSystemStateChangeNodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.StateUpdate <em>State Update</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.StateUpdate
   * @generated
   */
  public Adapter createStateUpdateAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.EndNode <em>End Node</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.EndNode
   * @generated
   */
  public Adapter createEndNodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.Or
   * @generated
   */
  public Adapter createOrAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.And
   * @generated
   */
  public Adapter createAndAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link net.mudcrab.coursework.mbsd.ifictiondsl.Parentheses <em>Parentheses</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see net.mudcrab.coursework.mbsd.ifictiondsl.Parentheses
   * @generated
   */
  public Adapter createParenthesesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //IfictiondslAdapterFactory
