/**
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.IfictiondslFactory
 * @model kind="package"
 * @generated
 */
public interface IfictiondslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ifictiondsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.seralyne.net/coursework/mdsd/ifictiondsl/Ifictiondsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ifictiondsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IfictiondslPackage eINSTANCE = net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl.init();

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StoryImpl <em>Story</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StoryImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getStory()
   * @generated
   */
  int STORY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__NAME = 0;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__NODES = 1;

  /**
   * The number of structural features of the '<em>Story</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.NodeImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getNode()
   * @generated
   */
  int NODE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NAME = 0;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ChoiceNodeImpl <em>Choice Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ChoiceNodeImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getChoiceNode()
   * @generated
   */
  int CHOICE_NODE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_NODE__NAME = NODE__NAME;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_NODE__OPTIONS = NODE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Choice Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ChoiceOptionImpl <em>Choice Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ChoiceOptionImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getChoiceOption()
   * @generated
   */
  int CHOICE_OPTION = 3;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_OPTION__TEXT = 0;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_OPTION__TRANSITIONS = 1;

  /**
   * The number of structural features of the '<em>Choice Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_OPTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.TransitionImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 4;

  /**
   * The feature id for the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__DESTINATION = 0;

  /**
   * The feature id for the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__PRIORITY = 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__CONDITION = 2;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StartNodeImpl <em>Start Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StartNodeImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getStartNode()
   * @generated
   */
  int START_NODE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_NODE__NAME = NODE__NAME;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_NODE__TEXT = NODE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_NODE__TRANSITION = NODE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Start Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.DialogueNodeImpl <em>Dialogue Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.DialogueNodeImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getDialogueNode()
   * @generated
   */
  int DIALOGUE_NODE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIALOGUE_NODE__NAME = NODE__NAME;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIALOGUE_NODE__TEXT = NODE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIALOGUE_NODE__TRANSITION = NODE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Dialogue Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIALOGUE_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ConditionImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 7;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ComparisonImpl <em>Comparison</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ComparisonImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getComparison()
   * @generated
   */
  int COMPARISON = 8;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__VARIABLE = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__OPERATOR = CONDITION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__VALUE = CONDITION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Comparison</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.SystemStateChangeNodeImpl <em>System State Change Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.SystemStateChangeNodeImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getSystemStateChangeNode()
   * @generated
   */
  int SYSTEM_STATE_CHANGE_NODE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_CHANGE_NODE__NAME = NODE__NAME;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_CHANGE_NODE__TEXT = NODE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>State Updates</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_CHANGE_NODE__STATE_UPDATES = NODE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_CHANGE_NODE__TRANSITION = NODE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>System State Change Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_CHANGE_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StateUpdateImpl <em>State Update</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StateUpdateImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getStateUpdate()
   * @generated
   */
  int STATE_UPDATE = 10;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_UPDATE__VARIABLE = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_UPDATE__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_UPDATE__VALUE = 2;

  /**
   * The number of structural features of the '<em>State Update</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_UPDATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.EndNodeImpl <em>End Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.EndNodeImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getEndNode()
   * @generated
   */
  int END_NODE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_NODE__NAME = NODE__NAME;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_NODE__TEXT = NODE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>End Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.OrImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getOr()
   * @generated
   */
  int OR = 12;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.AndImpl
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getAnd()
   * @generated
   */
  int AND = 13;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Story <em>Story</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Story</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Story
   * @generated
   */
  EClass getStory();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Story#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Story#getName()
   * @see #getStory()
   * @generated
   */
  EAttribute getStory_Name();

  /**
   * Returns the meta object for the containment reference list '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Story#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nodes</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Story#getNodes()
   * @see #getStory()
   * @generated
   */
  EReference getStory_Nodes();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Node#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Node#getName()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Name();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceNode <em>Choice Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choice Node</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceNode
   * @generated
   */
  EClass getChoiceNode();

  /**
   * Returns the meta object for the containment reference list '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceNode#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Options</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceNode#getOptions()
   * @see #getChoiceNode()
   * @generated
   */
  EReference getChoiceNode_Options();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceOption <em>Choice Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choice Option</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceOption
   * @generated
   */
  EClass getChoiceOption();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceOption#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceOption#getText()
   * @see #getChoiceOption()
   * @generated
   */
  EAttribute getChoiceOption_Text();

  /**
   * Returns the meta object for the containment reference list '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceOption#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.ChoiceOption#getTransitions()
   * @see #getChoiceOption()
   * @generated
   */
  EReference getChoiceOption_Transitions();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the reference '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Transition#getDestination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Destination</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Transition#getDestination()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Destination();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Transition#getPriority <em>Priority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Priority</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Transition#getPriority()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Priority();

  /**
   * Returns the meta object for the containment reference '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Transition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Transition#getCondition()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Condition();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StartNode <em>Start Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Start Node</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StartNode
   * @generated
   */
  EClass getStartNode();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StartNode#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StartNode#getText()
   * @see #getStartNode()
   * @generated
   */
  EAttribute getStartNode_Text();

  /**
   * Returns the meta object for the containment reference '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StartNode#getTransition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transition</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StartNode#getTransition()
   * @see #getStartNode()
   * @generated
   */
  EReference getStartNode_Transition();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.DialogueNode <em>Dialogue Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dialogue Node</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.DialogueNode
   * @generated
   */
  EClass getDialogueNode();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.DialogueNode#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.DialogueNode#getText()
   * @see #getDialogueNode()
   * @generated
   */
  EAttribute getDialogueNode_Text();

  /**
   * Returns the meta object for the containment reference '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.DialogueNode#getTransition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transition</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.DialogueNode#getTransition()
   * @see #getDialogueNode()
   * @generated
   */
  EReference getDialogueNode_Transition();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Comparison <em>Comparison</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Comparison
   * @generated
   */
  EClass getComparison();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Comparison#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Comparison#getVariable()
   * @see #getComparison()
   * @generated
   */
  EAttribute getComparison_Variable();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Comparison#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Comparison#getOperator()
   * @see #getComparison()
   * @generated
   */
  EAttribute getComparison_Operator();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Comparison#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Comparison#getValue()
   * @see #getComparison()
   * @generated
   */
  EAttribute getComparison_Value();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode <em>System State Change Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System State Change Node</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode
   * @generated
   */
  EClass getSystemStateChangeNode();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode#getText()
   * @see #getSystemStateChangeNode()
   * @generated
   */
  EAttribute getSystemStateChangeNode_Text();

  /**
   * Returns the meta object for the containment reference list '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode#getStateUpdates <em>State Updates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>State Updates</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode#getStateUpdates()
   * @see #getSystemStateChangeNode()
   * @generated
   */
  EReference getSystemStateChangeNode_StateUpdates();

  /**
   * Returns the meta object for the containment reference '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode#getTransition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transition</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode#getTransition()
   * @see #getSystemStateChangeNode()
   * @generated
   */
  EReference getSystemStateChangeNode_Transition();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate <em>State Update</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State Update</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate
   * @generated
   */
  EClass getStateUpdate();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getVariable()
   * @see #getStateUpdate()
   * @generated
   */
  EAttribute getStateUpdate_Variable();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getOperator()
   * @see #getStateUpdate()
   * @generated
   */
  EAttribute getStateUpdate_Operator();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getValue()
   * @see #getStateUpdate()
   * @generated
   */
  EAttribute getStateUpdate_Value();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.EndNode <em>End Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End Node</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.EndNode
   * @generated
   */
  EClass getEndNode();

  /**
   * Returns the meta object for the attribute '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.EndNode#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.EndNode#getText()
   * @see #getEndNode()
   * @generated
   */
  EAttribute getEndNode_Text();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Or#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Or#getLeft()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Or#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.Or#getRight()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Right();

  /**
   * Returns the meta object for class '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.And#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.And#getLeft()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.And#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.And#getRight()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IfictiondslFactory getIfictiondslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StoryImpl <em>Story</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StoryImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getStory()
     * @generated
     */
    EClass STORY = eINSTANCE.getStory();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORY__NAME = eINSTANCE.getStory_Name();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORY__NODES = eINSTANCE.getStory_Nodes();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.NodeImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NAME = eINSTANCE.getNode_Name();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ChoiceNodeImpl <em>Choice Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ChoiceNodeImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getChoiceNode()
     * @generated
     */
    EClass CHOICE_NODE = eINSTANCE.getChoiceNode();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE_NODE__OPTIONS = eINSTANCE.getChoiceNode_Options();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ChoiceOptionImpl <em>Choice Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ChoiceOptionImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getChoiceOption()
     * @generated
     */
    EClass CHOICE_OPTION = eINSTANCE.getChoiceOption();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOICE_OPTION__TEXT = eINSTANCE.getChoiceOption_Text();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE_OPTION__TRANSITIONS = eINSTANCE.getChoiceOption_Transitions();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.TransitionImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>Destination</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__DESTINATION = eINSTANCE.getTransition_Destination();

    /**
     * The meta object literal for the '<em><b>Priority</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__PRIORITY = eINSTANCE.getTransition_Priority();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__CONDITION = eINSTANCE.getTransition_Condition();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StartNodeImpl <em>Start Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StartNodeImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getStartNode()
     * @generated
     */
    EClass START_NODE = eINSTANCE.getStartNode();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute START_NODE__TEXT = eINSTANCE.getStartNode_Text();

    /**
     * The meta object literal for the '<em><b>Transition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START_NODE__TRANSITION = eINSTANCE.getStartNode_Transition();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.DialogueNodeImpl <em>Dialogue Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.DialogueNodeImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getDialogueNode()
     * @generated
     */
    EClass DIALOGUE_NODE = eINSTANCE.getDialogueNode();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIALOGUE_NODE__TEXT = eINSTANCE.getDialogueNode_Text();

    /**
     * The meta object literal for the '<em><b>Transition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIALOGUE_NODE__TRANSITION = eINSTANCE.getDialogueNode_Transition();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ConditionImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ComparisonImpl <em>Comparison</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.ComparisonImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getComparison()
     * @generated
     */
    EClass COMPARISON = eINSTANCE.getComparison();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON__VARIABLE = eINSTANCE.getComparison_Variable();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON__OPERATOR = eINSTANCE.getComparison_Operator();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON__VALUE = eINSTANCE.getComparison_Value();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.SystemStateChangeNodeImpl <em>System State Change Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.SystemStateChangeNodeImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getSystemStateChangeNode()
     * @generated
     */
    EClass SYSTEM_STATE_CHANGE_NODE = eINSTANCE.getSystemStateChangeNode();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_STATE_CHANGE_NODE__TEXT = eINSTANCE.getSystemStateChangeNode_Text();

    /**
     * The meta object literal for the '<em><b>State Updates</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_STATE_CHANGE_NODE__STATE_UPDATES = eINSTANCE.getSystemStateChangeNode_StateUpdates();

    /**
     * The meta object literal for the '<em><b>Transition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_STATE_CHANGE_NODE__TRANSITION = eINSTANCE.getSystemStateChangeNode_Transition();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StateUpdateImpl <em>State Update</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.StateUpdateImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getStateUpdate()
     * @generated
     */
    EClass STATE_UPDATE = eINSTANCE.getStateUpdate();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE_UPDATE__VARIABLE = eINSTANCE.getStateUpdate_Variable();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE_UPDATE__OPERATOR = eINSTANCE.getStateUpdate_Operator();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE_UPDATE__VALUE = eINSTANCE.getStateUpdate_Value();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.EndNodeImpl <em>End Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.EndNodeImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getEndNode()
     * @generated
     */
    EClass END_NODE = eINSTANCE.getEndNode();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute END_NODE__TEXT = eINSTANCE.getEndNode_Text();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.OrImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LEFT = eINSTANCE.getOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RIGHT = eINSTANCE.getOr_Right();

    /**
     * The meta object literal for the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.AndImpl
     * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.impl.IfictiondslPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAnd_Right();

  }

} //IfictiondslPackage
