/**
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State Update</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getVariable <em>Variable</em>}</li>
 *   <li>{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getOperator <em>Operator</em>}</li>
 *   <li>{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.IfictiondslPackage#getStateUpdate()
 * @model
 * @generated
 */
public interface StateUpdate extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' attribute.
   * @see #setVariable(String)
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.IfictiondslPackage#getStateUpdate_Variable()
   * @model
   * @generated
   */
  String getVariable();

  /**
   * Sets the value of the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getVariable <em>Variable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' attribute.
   * @see #getVariable()
   * @generated
   */
  void setVariable(String value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see #setOperator(String)
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.IfictiondslPackage#getStateUpdate_Operator()
   * @model
   * @generated
   */
  String getOperator();

  /**
   * Sets the value of the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see #getOperator()
   * @generated
   */
  void setOperator(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.IfictiondslPackage#getStateUpdate_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // StateUpdate
