/**
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System State Change Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode#getText <em>Text</em>}</li>
 *   <li>{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode#getStateUpdates <em>State Updates</em>}</li>
 *   <li>{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode#getTransition <em>Transition</em>}</li>
 * </ul>
 *
 * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.IfictiondslPackage#getSystemStateChangeNode()
 * @model
 * @generated
 */
public interface SystemStateChangeNode extends Node
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.IfictiondslPackage#getSystemStateChangeNode_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>State Updates</b></em>' containment reference list.
   * The list contents are of type {@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.StateUpdate}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State Updates</em>' containment reference list.
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.IfictiondslPackage#getSystemStateChangeNode_StateUpdates()
   * @model containment="true"
   * @generated
   */
  EList<StateUpdate> getStateUpdates();

  /**
   * Returns the value of the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transition</em>' containment reference.
   * @see #setTransition(Transition)
   * @see net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.IfictiondslPackage#getSystemStateChangeNode_Transition()
   * @model containment="true"
   * @generated
   */
  Transition getTransition();

  /**
   * Sets the value of the '{@link net.seralyne.coursework.mdsd.ifictiondsl.ifictiondsl.SystemStateChangeNode#getTransition <em>Transition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transition</em>' containment reference.
   * @see #getTransition()
   * @generated
   */
  void setTransition(Transition value);

} // SystemStateChangeNode
