/*
 * generated by Xtext 2.42.0
 */
package net.seralyne.coursework.mdsd.ifictiondsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import net.seralyne.coursework.mdsd.ifictiondsl.IfictiondslRuntimeModule;
import net.seralyne.coursework.mdsd.ifictiondsl.IfictiondslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class IfictiondslIdeSetup extends IfictiondslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new IfictiondslRuntimeModule(), new IfictiondslIdeModule()));
	}
	
}
